### ISSUE TITLE
[QUESTION] add_middleware code question

### ISSUE THREAD

**Issue by uvicorn** [Kludex/starlette#1092]
Hi! 
In this [code](https://github.com/encode/starlette/blob/b95acea973c20eea3e7cbbca42d09b1f5d4a3412/starlette/applications.py#L126) you add middleware to 0 index in stack, but in [this code](https://github.com/encode/starlette/blob/b95acea973c20eea3e7cbbca42d09b1f5d4a3412/starlette/applications.py#L90) you build middleware stack
 with reverse list of middlewares... WUT? 

That is, adding add middleware goes at the 0 index of the list, but at the same time initialization goes in the normal order

**Comment by uvicorn** [comment]
what for? there is some kind of sacral meaning?

**Comment by goduni** [comment]
hey, i am with the same question, what secret meaning is hidden here

**Comment by porterdarby** [comment]
Based on my understanding, it's because you want to order it like an onion with the router right in the center.

Starting with [`app = self.router`](https://github.com/encode/starlette/blob/b95acea973c20eea3e7cbbca42d09b1f5d4a3412/starlette/applications.py#L89) (generated in the [`__init__` method](https://github.com/encode/starlette/blob/b95acea973c20eea3e7cbbca42d09b1f5d4a3412/starlette/applications.py#L59-L61)), we apply each individual middleware in the list of `middleware` via [`app = cls(app=app, **options)`](https://github.com/encode/starlette/blob/b95acea973c20eea3e7cbbca42d09b1f5d4a3412/starlette/applications.py#L91), and eventually return the `app`, assuming you aren't using a reversed `middleware` list.

The problem with this is that it creates a LIFO sort of situation -- the first middleware is applied first, but when the application actually handles a request against the `app`, it's the last one to actually run. This means that if you set up your middleware stack as follows:

1. ServerErrorMiddleware
1. UserMiddleware1
1. UserMiddleware2
1. ExceptionMiddleware

Then when a new request would be handled in this order:

1. ExceptionMiddleware
1. UserMiddleware2
1. UserMiddleware1
1. ServerErrorMiddleware

This can cause a problem -- if a UserMiddleware needs to produce a server error, nothing before it in the callstack can handle it. Alternatively, if you require that UserMiddleware1 runs before UserMiddleware2, then there is nothing you can do to fix that.

The answer is reversing. In a reversed list, you'll end up applying the last middleware, first in the `build_middleware_stack` method, which means that it will be applied last when a request comes in.
