### ISSUE TITLE
Custom 500 or Exception handlers do not run through middleware like other handled exceptions.

### ISSUE THREAD

**Issue by danielknell** [Kludex/starlette#1175]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### To reproduce

```python
from starlette.applications import Starlette
from starlette.middleware import Middleware
from starlette.middleware.cors import CORSMiddleware
from starlette.responses import JSONResponse

app = Starlette(routes=routes, middleware=middleware)

async def not_found(request, exc):
    return JSONResponse(content={"error": 404}, status_code=exc.status_code)

async def server_error(request, exc):
    return JSONResponse(content={"error": 500}, status_code=exc.status_code)

exception_handlers = {
    404: not_found,
    500: server_error
}

middleware = [
    Middleware(CORSMiddleware, allow_origins=['*'])
]

app = Starlette(routes=routes, middleware=middleware, exception_handlers=exception_handlers)
```

### Expected behavior

both 404 and 500 errors will respond with their relevant json response, and correct CORS headers

### Actual behavior

the 404 error will response with correct CORS headers but the 500 error will not.

### Debugging material

Because `Exception` and `500` are special cased in `build_middleware_stack` any error bubbles up to the outer most `ServerErrorMiddleware` which is outside the other middleware, instead of being handled by the `ExceptionMiddleware` and passing through the custom middleware.

see: https://github.com/encode/starlette/blob/master/starlette/applications.py#L74-L77

I can see four possible fixes, none of them perfect...

- handle custom 500 errors in `ExceptionMiddleware` and prevent `ServerErrorMiddleware` showing its helpful debug info when a custom handler is present.
- have `ServerErrorMiddleware` run the response of the error handler through the middleware stack again, and if that fails resort to existing behaviour, adding a bunch of complexity.
- move the debuging info to a separate middleware and put that in front of the ErrorMiddleware, which would then cause it to trigger for every exception, but would allow `ExceptionMiddleware` handle 500s as expected, and `ServerErrorMiddleware` becomes a last resort.
- update https://www.starlette.io/exceptions/ to explain 500 errors are handled differently, and to get the above behaviour something like the following work-around is required:

  ```py
  @app.middleware("http")
  def exception_middleware(request, call_next)
      try:
          return await call_next(request)
      except Exception:
          return JSONResponse(content={"error": 500}, status_code=500))
  ```

### Environment

- OS: N/A
- Python version: N/A
- Starlette version: 0.13.6 and master branch

### Additional Context

#1116  seems to be have similar but refers to the generic `error_response` on `ServerErrorMiddleware`, this is similar but specifically about custom error handlers so i didn't want to hijack that issue.

**Comment by danielknell** [comment]
thinking about this more something like the following would behave as expected?

```py
    def build_middleware_stack(self) -> ASGIApp:
        debug = self.debug
        error_handler = None
        exception_handlers = {}

        for key, value in self.exception_handlers.items():
            if not debug or key not in (500, Exception):
                exception_handlers[key] = value

        middleware = (
            [Middleware(ServerErrorMiddleware, debug=debug)]
            + self.user_middleware
            + [
                Middleware(
                    ExceptionMiddleware, handlers=exception_handlers, debug=debug
                )
            ]
        )

        app = self.router
        for cls, options in reversed(middleware):
            app = cls(app=app, **options)
        return app
```

when `debug == True` unhandled errors will bubble up to the `ServerErrorMiddleware` and render as expected, but when `debug == False`, they will be handled in the `ErrorMiddleware` like normal? should i find time to put a PR together?

**Comment by jcwilson** [comment]
I'm not sure I'd want the `debug` flag being the arbiter of behavior here. I'd want the behavior to be consistent across development and production. It seems to me that starlette is being overly prescriptive in the way it handles unexpected errors. (not to say it's not already pretty flexible, but just that it could be improved).

I commented on the #1116 and put up a straw-man PR focusing on the CORS issue. Ultimately, I think we need to have a way to add middleware layers outside of the implicit builtin `ServerErrorMiddleware`, at least for response manipulation. I like the guarantee that `ServerErrorMiddleware` provides - that a `Response` object will have been created and invoked. Being able to configure further response processing would provide a natural place to apply the `CORSMiddleware` with minimal changes to the cors module.

**Comment by haynesgt** [comment]
~~The suggested middle workaround (with ...def exception_middleware...) is a bit inadequate because starlette [erases the cause of exceptions that have no handler](https://github.com/encode/starlette/blob/master/starlette/exceptions.py#L82) (no idea why -- that might be another issue).~~ nvm this was fixed in recent starlette, but there is another issue where the task seems to get cancelled and the custom middleware can't handle the exception

**Comment by lovelydinosaur** [comment]
> the 404 error will response with correct CORS headers but the 500 error will not.

That... seems totally okay to me.

If you have an *unhandled* exception you really do just want to break out with a 500 error, with minimal other interference.

It's a broken state that you do want to see, and it shouldn't at all matter what CORS headers it does or doesn't include.

(Also it'd be perfectly possible for the user to get a 5xx response from some intermediary, such as an overloaded server, or a gateway proxy, and you wouldn't be seeing any CORS headers on those either)

**Comment by JimDabell** [comment]
We serialise errors to Problem JSON format and display them in the browser, including 500 errors. Just because an error has occurred on the server, it doesn’t mean that you can’t show a useful error to the user containing the details of what has gone wrong. Right now, the obvious approach you get from following the documentation fails. Instead you need a clumsy workaround that goes against the documentation’s recommendation.

> It's a broken state that you do want to see

That’s precisely the point. If you have an SPA loading API requests and there is a 500 error, the CORS headers are what allows you to see what is going on with the broken state, instead of just "Sorry, something failed but I can’t tell you what because I’m not allowed to look at the details”.

**Comment by lovelydinosaur** [comment]
Ah thanks @JimDabell - that *does* make some sense.

> Just because an error has occurred on the server, it doesn’t mean that you can’t show a useful error to the user containing the details of what has gone wrong.

Right, which we *do*. (Proviso: but only if you're in debug mode. If you hit a server error on prod you don't want to expose any of that info in the response, but you will want to be monitoring it with something like Sentry)

> If you have an SPA loading API requests and there is a 500 error, the CORS headers are what allows you to see what is going on with the broken state, instead of just "Sorry, something failed but I can’t tell you what because I’m not allowed to look at the details”.

Gotcha - I'd not figured that.

Is there a liberal header policy that can be used in that case, perhaps?

I'm pretty sure Django's error handling has a similar style to what I've just described. I don't know about flask. How do they deal with this particular use-case?

**Comment by JimDabell** [comment]
I don’t think a specific policy is desirable – we just need the policy we have already specified with the CORS middleware to be applied to 5xx errors the same way it is to 4xx errors.

**Comment by lovelydinosaur** [comment]
So, if you *really* want to do that, then wrap the middleware around the entire app...

```python
# Make sure the entire app is wrapped up in CORSMiddleware,
# including 5xx error responses.
app = Starlette(...)
app = CORSMiddleware(app, ...)
```

**Comment by josheppinette** [comment]
I understand the reasoning. However, a downside of this is that in local development, when `Debug is True` the only exception output is included in the response body which won't be translated to the client due to a CORS error.

**Comment by lazyBisa** [comment]
I am struggling with this problem right now too.   
As I understand it, the `ExceptionMiddleware` is supposed to catch and handle errors that happen in the application scope (i.e. my s3 adapter throws exceptions). This may of course include exceptions unknown to me, so allowing for a catch-all handler that can still pass stuff through the rest of the middleware stack is certainly helpful.  
The `ServerErrorMiddleware` on the other hand is supposed to intercept, and maybe act uppon, but not catch and possibly resolve (mind the rethrow!) exceptions happening in the Middleware stack, or otherwise not accounted for (which admittedly *should* not happen).

Consequently, I would expect a `@app.exception_handler(Exception)` be the 'catch-all' case in the Exception middleware, with the handler in the ServerErrorMiddleware being configured by e.g. `@app.server_exception_handler()`.  
The hidden behaviour of moving select Exception Handlers to the other side of the middleware stack certainly feels counter-intuitive.
It might also have implications on middleware design. E.g. a monitoring middleware might have to assume(!) that exceptions will be converted to a 500 response and needs to count them as such in addition to the 'normal' 500s.

My explicit problem right now is that the prometheus-fastapi-instrumentor is removing `__cause__` from exceptions that travel through the middleware. In the ServerErrorMiddleware, the exception then lacks info I need to correctly log the error. My solution is to manually instantiate and configure another ExceptionMiddleware right behind the standard one.
```python
app = FastAPI(title="My App")
app.add_middleware(
    ExceptionMiddleware,
    handlers={Exception: unexpected_exception_handler},
    debug=app.debug,
)
```

Imho, application.py ln 74-77 looks kinda smelly. Ofc, that can't be changed without breaking backward compatibility.

**Comment by JonasKs** [comment]
> So, if you _really_ want to do that, then wrap the middleware around the entire app...
> 
> ```python
> # Make sure the entire app is wrapped up in CORSMiddleware,
> # including 5xx error responses.
> app = Starlette(...)
> app = CORSMiddleware(app, ...)
> ```

This is _almost_ what we would like, yes. For middlewares such as [`asgi-correlation-id`](https://github.com/snok/asgi-correlation-id), you want them to always be run after any other exception handling has been done. Your approach require us to run `uvicorn` on the `CORSMiddleware` which wraps the `Starlette` app, which feels a bit weird.

The problem is essentially that the middleware stack looks like this:

```python
FastAPI.middleware_stack
-> ServerErrorMiddleware
  -> CorrelationIdMiddleware
    -> CorsMiddleware
```
and that the `ServerErrorMiddleware` overrides all headers. So now, any uncaught exception has all its headers stripped. For correlation (and sometimes CORS), we would want these headers to still be applied for uncaught errors. 

There's two solutions to the problem:
1. Allow `ServerErrorMiddleware` to be configured to keep headers
2. Allow us to explicitly pass in middlewares that will take the outermost middleware spots

The second option would allow us to build a middleware stack like this:
```python
FastAPI.middleware_stack
-> CorrelationIdMiddleware
  -> CORSMiddleware
    -> ServerErrorMiddleware
```

Since there is no way to do this nicely (but I'm happy to come with a PR if you accept one of the solutions), I've written a little util to patch this behavior, achieving option 2.

1. Install [`fastapi-stack-utils`](https://github.com/JonasKs/fastapi-stack-utils/tree/main) 
2. Add [patch_fastapi_middlewares](https://github.com/JonasKs/fastapi-stack-utils/blob/main/fastapi_stack_utils/middleware.py#L16-L60) _before_  `FastAPI`/`Starlette`, passing in the list of `Middleware()` you'd like to be further out than `ServerErrorMiddleware`.

```python 
from fastapi_stack_utils.middleware import patch_fastapi_middlewares
patch_fastapi_middlewares(  # this must be done _before_  FastAPI is initialized
    middlewares=[
        Middleware(
            CORSMiddleware,
            allow_credentials=True,
            allow_headers=['*'],
            allow_methods=['*'],
            allow_origins=['*'],
        ),
        Middleware(CorrelationIdMiddleware, header_name='Correlation-ID')
    ]
)
app = FastAPI(...)
```

**Comment by adriangb** [comment]
> Your approach require us to run uvicorn on the CORSMiddleware which wraps the Starlette app, which feels a bit weird.

Edit: I probably responded too quickly. There's a lot of nuance in this thread.

There is nothing weird about this. That is a FastAPI doe me internally and it is how the ASGI spec was designed.

**Comment by JonasKs** [comment]
I get that its compliant, so "weird" was bad word to use. 

I wanted to underline that this approach would force me to have multiple applications defined in `main.py`:
```
app = FastAPI()
cors_app = CORSMiddleware(app, ...)
``` 
so that I could write `from main import app` and actually get the FastAPI instance (in case we'd like to use e.g. `app.include_router`), while `uvicorn` would be pointed to the `cors_app`. This _feels_ weird to me.

**Comment by adriangb** [comment]
Okay I think I've read through the thread.

@JonasKs I still don't think there's anything wrong with that. FWIW, if I were to see this in a code review I think I might ask for a one line comment explaining why we are doing it but other than that I would be perfectly happy with that.

I do think not moving 500/Exception handlers into ServerErrorMiddleware seems reasonable ("handle custom 500 errors in ExceptionMiddleware and prevent ServerErrorMiddleware showing its helpful debug info when a custom handler is present").

I also wonder if one could wrap CORSMiddleware with ExceptionMiddleware, I'll give it a quick shot.

**Comment by adriangb** [comment]
Yeah I think what I would do if I _really_ needed this behavior would be to manually insert an `ExceptionMiddleware(..., handlers={Exception: custom_server_error_middleware})` somewhere in the middleware stack before the middleware I want to be able to handle uncaught exceptions, just like @lazyBisa suggested.

But like Tom said, there is a lot to be said for _not_ doing any extra processing for uncaught exceptions.

**Comment by babymastodon** [comment]
Hi folks. I realize that people on this thread have already mentioned this multiple times, but I would like to +1 that the removal of CORS headers from 500 exceptions is a huge inconvenience for those of us who are developing single page apps. Unless one disables cross-origin-security-checking in Google Chrome, or wraps the entire app in `CORSMiddleware`, it is not possible to return a 500 error to the the web browser. While this could be reasonable in production (since we want to hide the error from the user regardless), it slows down developers who are working on the single page app, as they are unable to view backend errors directly from the browser.

Even if we cannot solve the general problem of making 500 exceptions available to all middlewares, I think it would be a net win if we can solve the problem specifically for the `CORSMiddleware`, and even if it's only enabled in debug mode. Reducing the scope might make the problem a bit more tractable, and reduce the risks involved with allowing arbitrary processing for uncaught exceptions.

**Comment by vibpe** [comment]
+1 There is absolutely no reason to remove the CORS headers. 

If you want to hide the error details (5xx or 4xx) from normal users, then it is a frontend task to prettify the message for the user. 

On the other hand you definitely want to hide the internal exception details from attackers. But the removal of CORS headers does not stop anyone who can open the browsers developer tools. Even without CORS headers attackers can see the response body. The response body must not contain any sensitive information and this has nothing to do with CORS headers.

**Comment by reallistic** [comment]
>  don't know about flask. How do they deal with this particular use-case?

@tomchristie flask separates middleware activities into a few different handlers (some are listed below). This enables flask first to run the error handlers, including the default "unhandled" case, and _then_ run response processing to e.g. add cors headers. Also, flask does have some magic to move `Exception` handlers to the end, but this is done via the custom `InternalServerError`(4) exception, which can be specified in `@app.errorhandler`(1) registration.

Starlette could potentially reverse this methodology to help out here. Would you be open to something like this?

```python
# starlette/exceptions.py

class InternalException(Exception):
    def __init__(self, original_exception: Exception):
        self.original_exception = original_exception

class ExceptionMiddleware:
    async def __call__(...) -> None:
       ...
        try:
            await self.app(scope, receive, sender)
        except Exception as exc:
            handler = None

            # existing handler lookup cases
            ...

            if handler is None:
                internal_exc = InternalException(exc)
                handler = self.lookup_exception_handler(internal_exc)
                if handler:
                    exc = internal_exc

            if handler is None:
                raise exc from None

# usage:
from starlette.exceptions import InternalException

def handle_unhandled(req: Request, exc: InternalException):
    record_metrics(exc=exc.original_exception)
    return JSONResponse(content={"error": 500}, status_code=500)

app = Starlette(...)
app.add_exception_handler(InternalException, handle_unhandled)
```


1. [`@app.errorhandler`](https://flask.palletsprojects.com/en/2.2.x/api/#flask.Flask.errorhandler)
2. [`@app.before_request`](https://flask.palletsprojects.com/en/2.2.x/api/#flask.Flask.before_request)
3. [`@app.after_request`](https://flask.palletsprojects.com/en/2.2.x/api/#flask.Flask.after_request)
4. [`app.handle_exception`](https://flask.palletsprojects.com/en/2.2.x/api/#flask.Flask.handle_exception) - NOTE: support for this case was added in version 1.1.0 as mentioned in the docs.
5. [flask_cors](https://github.com/corydolphin/flask-cors/blob/master/flask_cors/extension.py#L162) uses `@app.after_request`

**Comment by phillipuniverse** [comment]
For anybody else that comes across this issue from Google/etc - Starlette has docs that [recommends wrapping the final app in `CORSMiddleware`](https://starlette.dev/middleware/#corsmiddleware-global-enforcement) added in #2885.

> The recommended solution is to wrap the entire Starlette application with CORSMiddleware. This approach guarantees that even if an exception is caught by ServerErrorMiddleware (or other outer error-handling middleware), the response will still include the proper Access-Control-Allow-Origin header.
