### ISSUE TITLE
JSONResponse allows types other than dict to be serialized without an explicit opt in

### ISSUE THREAD

**Issue by graingert** [Kludex/starlette#1231]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

JSONResponses that are not dicts have a number of disadvantages, such as violating SOP on ES5 browsers and preventing future extension

### Additional context

django does this https://github.com/django/django/blob/ca9872905559026af82000e46cde6f7dedc897b6/django/http/response.py#L579-L604

https://twitter.com/simonw/status/1410682522908856320

**Comment by JayH5** [comment]
Maybe another case of this producing confusing behaviour: https://github.com/tiangolo/fastapi/issues/2832#issuecomment-781595594

**Comment by adriangb** [comment]
I thought that with modern standards non object/array JSON is okay?

**Comment by lovelydinosaur** [comment]
Once upon a time, in the long distant past, there was some security thingumy to do with returning lists. I don't recall it now, but I'm pretty such it's been fixed for a while now. I think we're *fine* with returning *whatever*, but it'd be neat for `JSONResponse()` and `JSONResponse(None)` to actually just mean "no content", rather than `null`.

**Comment by graingert** [comment]
Returning a list rather than an object is a footgun that prevents future compatibility in JSON responses (which is the real reason why django warns rather than the old security issue)

**Comment by adriangb** [comment]
Do you have any resources I can read on that Thomas? I don't currently understand how that breaks things for browsers, but I would like to.

**Comment by chbndrhnns** [comment]
I am not @graingert but I remember reading http://haacked.com/archive/2009/06/25/json-hijacking.aspx/ and https://stackoverflow.com/questions/3503102/what-are-top-level-json-arrays-and-why-are-they-a-security-risk on that topic.

**Comment by lovelydinosaur** [comment]
Indeed it's a nicer style.

@adriangb I don't know about resources, but essentially it's a neater API style to *always* return dicts at the top-level, because it means that they're more extensible if you want/need to add some extra info at a later date.

Which is... good advice, but not *necessarily* something we'd want Starlette to hard-enforce. (Or to switch behaviour on)

**Comment by adriangb** [comment]
Right agreed it's good  practice! And it's what I'd do in any real app. The only situation in which I find myself returning something else is tests. But from above it sounded like there's issues that go deeper than good design, I wasn't aware of them so just hoping to learn something. But it seems like indeed the main remaining reason is that it's a footgun for users that aren't aware of the consequences of returning a non-extensible response. In that case I agree with @tomchristie: I'm not sure I'd want that enforced on me.
