### ISSUE TITLE
Could  JSONResponse  provide  JsonEncoder class option on    JSONResponse.__init__ () ?

### ISSUE THREAD

**Issue by lishukan** [Kludex/starlette#1250]
Hi,dear  commiter:
     When I use the class  -- <JsonResponse>  to serialize(jsonify) a response, I find that I can not assign the special JsonEncoder .  Sometime i have to rewrite the JsonResponse class  ,like  following code
`class JSONResponse(Response):
    media_type = "application/json"

    def __init__(self,*args,**kwargs):
        self.encoder = kwargs.get('encoder',None)
        super().__init__(*args)

    def render(self, content: typing.Any) -> bytes:
        return json.dumps(
            content,
            ensure_ascii=False,
            allow_nan=False,
            indent=None,
            separators=(",", ":"),
            cls=self.encoder,
        ).encode("utf-8")`

 i think it's  necessary that provide custom jsonencoder function.

**Comment by Kludex** [comment]
It feels weird to add the encoder on the `init`, because you usually want to reuse the Response class, and with this you'll have to use the `encoder=Encoder` on every endpoint. :thinking: 

I'm going to take the lead here, and close this issue. Below is the current alternative for the proposed snippet:

```python
class CustomJSONResponse(Response):
    media_type = "application/json"
    encoder = Encoder

    def render(self, content: typing.Any) -> bytes:
        return json.dumps(
            content,
            ensure_ascii=False,
            allow_nan=False,
            indent=None,
            separators=(",", ":"),
            cls=self.encoder,
        ).encode("utf-8")
```

In case someone disagrees with my statement, feel free to start a discussion on our Gitter or reopen the issue.

**Comment by Kludex** [comment]
Related #715
