### ISSUE TITLE
Inconsistent Typing Between request.url_for and application.url_path_for

### ISSUE THREAD

**Issue by cancan101** [Kludex/starlette#1319]
[`request.url_for` takes `Any` for the `path_params`](https://github.com/encode/starlette/blob/217019b36303ea16a5869ad076d835e4fdc1cef3/starlette/requests.py#L168) whereas [`application.url_path_for` expects `path_params` to be `str`](https://github.com/encode/starlette/blob/537ab6afd110b79dca95f3c8ecc6980710b1de1c/starlette/applications.py#L107). Likewise the route / routers expect `path_params` to be `str`. See [here](https://github.com/encode/starlette/blob/537ab6afd110b79dca95f3c8ecc6980710b1de1c/starlette/routing.py#L159) and [here](https://github.com/encode/starlette/blob/537ab6afd110b79dca95f3c8ecc6980710b1de1c/starlette/routing.py#L584).

The type mismatch is not caught by the type checker as the `router` here is untyped:
https://github.com/encode/starlette/blob/217019b36303ea16a5869ad076d835e4fdc1cef3/starlette/requests.py#L169-L170

I think `Any` is probably more close to being the correct type as the `path_params` can be `UUID`, `int`, etc.

[The docs](https://www.starlette.io/routing/#reverse-url-lookups) would make it seems that the API for these two methods should have a consistent signature.

**Comment by Kludex** [comment]
> The type mismatch is not caught by the type checker as the `router` here is untyped:

The argumentation above is not true: https://github.com/encode/starlette/pull/1344

I'll review more carefully later on.

**Comment by aminalaee** [comment]
I think that argument is not true, but to reproduce the issue we should consider this:

Mypy doesn't catch this (maybe expected behaviour?):

```python
import typing

def a(**kwargs: int):
    print(kwargs)


def b(**kwargs: typing.Any):
    a(**kwargs)


b(s="2")
```

Mypy doesn't catch any issues with this, but we pass Any to `b` and pass that to `a` which expects int and should be caught.


https://github.com/encode/starlette/blob/217019b36303ea16a5869ad076d835e4fdc1cef3/starlette/requests.py#L167-L170

In this case I think we're doing the same thing. The `url_for` takes `Any` and passes that to `router.url_for` which expects `str` but mypy doesn't complain. Since `Any` is compatible with `str`.


P.S. I asked this on `mypy` gitter and this is the expected behaviour since `Any` is compatible with `str` or `int` or anything else.
