### ISSUE TITLE
redirect_slashes not respecting HTTPS

### ISSUE THREAD

**Issue by bentheiii** [Kludex/starlette#1396]
### Checklist

- [x] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

If an HTTPS request causes a slash redirect, the https schema is not preserved in the "location" header in the response.
This is especially important for environments that don't allow http requests. In such cases all slash-missing requests will fail with a 426 response.

### Steps to reproduce the bug

1. create a server that can handle HTTPS requests
2. create a url "/foo", make sure that redirect_slashes is "True"
3. make an https request to "/foo/"
4. note the response location

### Expected behavior

the "location" header in the response should be to "https://../foo"

### Actual behavior

the "location" header in the response is actually "http://../foo"

### Environment

observed in linux/ python 3.8/ starlette version 0.17.1

**Comment by aminalaee** [comment]
Hi,

I'm not able to reproduce the issue with this example:

```python
from starlette.applications import Starlette
from starlette.responses import PlainTextResponse
from starlette.routing import Route, Router


async def example(request):
    return PlainTextResponse("Example")


router = Router(
    routes=[
        Route("/example", endpoint=example),
    ],
    redirect_slashes=True,
)

app = Starlette(routes=router.routes)
```

And running HTTPS on localhost using Caddy, this is the result:

![Screenshot 2022-01-18 at 10 38 38](https://user-images.githubusercontent.com/19784933/149911324-d7d5a448-dffc-4941-b71e-69000c0c6d1b.png)

**Comment by aminalaee** [comment]
@bentheiii Can you update the issue?

**Comment by bentheiii** [comment]
Apologies, I now tried to recreate the bug on a different machine and it appears to be resolved. I will continue investigating, if I find that it has to do with starlette, I will reopen.

**Comment by aminalaee** [comment]
No problem.

**Comment by labbati** [comment]
A note for whoever has a similar issue in the future.

As of today, in order to honor https on redirects I had to run `uvicorn` with the `--proxy-headers --forwarded-allow-ips *` options. This way `uvicorn` will use `X-Forwarded-Proto` to set the ASGI scope's scheme ([code](https://github.com/encode/uvicorn/blob/a2219eb2ed2bbda4143a0fb18c4b0578881b1ae8/uvicorn/middleware/proxy_headers.py#L47-L57)).

The reason why @aminalaee wasn't able to replicate (possibly) is because in his example `scope['client']` gets set to `127.0.0.1` which is [trusted by default](https://github.com/encode/uvicorn/blob/a2219eb2ed2bbda4143a0fb18c4b0578881b1ae8/uvicorn/middleware/proxy_headers.py#L22).

I believe that there are a couple of issues here, though:
1. I do not like that with this approach, I am also forced to [forward the client's IP](https://github.com/encode/uvicorn/blob/a2219eb2ed2bbda4143a0fb18c4b0578881b1ae8/uvicorn/middleware/proxy_headers.py#L59), which has security concerns. However, this is `uvicorn`'s decision, and out of scope here.
2. I do not see a scenario why, when starlette receives in a scope both `scope['scheme']: http` and a header `'(x-forwarded-proto', b'https')`, then it should blindly pick `scope['scheme']: http` instead of using the one from the header to decide the scheme (see an example of a _broken_ scope below). But maybe there are reasons I cannot think of right now.

```
scope = {
    'type': 'http',
    'asgi': {
        'version': '3.0',
        'spec_version': '2.4'
    },
    'http_version': '1.1',
    'server': ('172.26.0.3', 8000),
    'client': ('172.26.0.2', 47402),
    'scheme': 'http',
    'method': 'GET',
    'root_path': '',
    'path': '/some-path',
    'raw_path': b'/some-path',
    'query_string': b'',
    'headers': [
        (b'host', b'feelyoudo.com'),
        (b'user-agent', b'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'),
        (b'accept', b'*/*'),
        (b'accept-encoding', b'deflate, gzip'),
        (b'accept-language', b'zh-CN'),
        (b'cookie', b''),
        (b'referer', b'https://mydomain.com/some-path'),
        (b'x-forwarded-for', b'111.222.333.444'),
        (b'x-forwarded-host', b'mydomain.com'),
        (b'x-forwarded-port', b'443'),
        (b'x-forwarded-proto', b'https'),
        (b'x-forwarded-server', b'ff3e8bd7374b'),
        (b'x-real-ip', b'111.222.333.444')
    ],
    'state': {},
    'app': '<starlette.applications.Starlette object at 0x7f6256f535f0>'
}
```
