### ISSUE TITLE
Support for python 3.5.

### ISSUE THREAD

**Issue by manatlan** [Kludex/starlette#187]
Hi ...

It seems that starlette is py>=3.6 .... so it doesn't work with python3.5, and so raspberry/raspbian (py3.5.3) ;-(
Is it just the f-string which block that ? or it's anything else ?

If it's just fstring : I can propose patchs ...

Thanks in advance

**Comment by extraymond** [comment]
Will this be possible by writing a instance with __aiter__ and __anext__?

I'm not sure if functionally wised they are the same as async generator though.

**Comment by lovelydinosaur** [comment]
@extraymond Yes I believe so. That'd be the fix.

**Comment by lovelydinosaur** [comment]
If someone wanted to help progress this then the sensible thing to do would be:

* Create a pull request that adds python 3.5 to the travis builds.
* Either comment out any code that's a syntax error in 3.5, or add test skip markers, until all the remaining tests are passing.

That'll then isolate for us *exactly* what code would need alteration in order to work with 3.5, and we could take next steps from there.

**Comment by extraymond** [comment]
@tomchristie  Thx for the tips!

After fiddling around with pypy3.5, I found the following todo-items for pypy compatible.

**1. yield syntax inside starlette.request or such**

1. Replace yield with __aiter__, __anext__ in a  class or use [async_generator package](https://pypi.org/project/async_generator/) to maintain minimal changes.
2. If using async_generator, output type is changing from typing.AsyncGenerator to the async_generator one. Since starlette.request is used in all majority of starlette, this breaks a lot of type checking stuff.

I'm not sure whether its good idea to use class based async_generator, or just use the package to maintain minimal code changes. Would love to know what's your idea on solving this.

**2. typing.Namedtuple behavior in 3.5**

For **starlette.schemas.EndpointInfo**, it should be declared with 

```python
EndpointInfo = typing.NamedTuple('EndpointInfo',
    [
     ('path', str),
     ('http_method', str),
     ('func', typing.Callable)
    ])
```

**Comment by lovelydinosaur** [comment]
> Would love to know what's your idea on solving this.

I wouldn't want the additional dependency there.

(So: Implement it as a class)

**Comment by lovelydinosaur** [comment]
> Replace yield with aiter, aexit in a class

Okay, I guess the next thing would be giving a brief example of how that might look (even if it's not completely implemented, and is just a code snippet on this thread, that'd still be useful)

**Comment by extraymond** [comment]
Example for starlette.request.Request.stream

```python
class async_stream:

    def __init__(self, request):
        """Use internal checker to skip behaviour."""

        self.req = request
        self.phase = 0
        self.chk = False

    async def __aiter__(self):
        return self

    async def __anext__(self):
        """ Return the next stream.
        Use StopAsyncIteration to cancel iterator.
        Equivalent to "return" in a generator function.
        """

        if self.phase == 0:
            if not self.chk:
                if hasattr(self.req, "_body"):
                    self.chk = True
                    return self._body
            else:
                self.step += 1
                self.chk = True
                raise StopAsyncIteration

        elif self.phase == 1:
            if self.req._stream_consumed:
                raise RuntimeError("Stream consumed")
            self.req._stream_consumed = True
            self.phase += 1

        elif self.phase == 2:
            if not self.chk:
                message = await self.req._receive()
                if message["type"] == "http.request":
                    body = message.get("body", b"")
                    if body:
                        return body
                    if not message.get("more_body", False):
                        self.chk = True
                elif message["type"] == "http.disconnect":
                    raise ClientDisconnect()
            else:
                self.phase += 1

        elif self.phase == 3:
            return b""
        else:
            raise StopAsyncIteration

```

Example of using the stream in this.

```python

asnc def async_func(request):
    async for stream in async_stream(request):
        print(stream)
```

A bit messy for using internal phase and checker, but the output behavior should be similar to async generator using yield. I'm still thinking about how to do this properly since using internal checker might hurt performance of request.

**Comment by lovelydinosaur** [comment]
Bzztt.

**Comment by lovelydinosaur** [comment]
Pass.

**Comment by lovelydinosaur** [comment]
I guess I *might* consider this if we had a bit of conditional code to only include it for 3.5 and to instead include the standard stuff for 3.6+.

If anyone wanted to try out a proof-of-concept pull request, that'd allow us to make a decision on it.
It'd be nice to be able to run on a raspberry pi, and it'd also bring our versions in sync with uvicorn, and allow us to just use the Starlette test client for some of the Uvicorn tests.

**Comment by em92** [comment]
Started porting starlette to python 3.5
https://github.com/em92/starlette/tree/python35-port

Using external `async_generator` package, mentioned in https://github.com/encode/starlette/issues/187#issuecomment-445265016

Currently tests are running, but some of them are failing. For example:
https://github.com/encode/starlette/blob/0c3a1e4a604a21bf615b0d9d93ad2070ff77edb7/tests/test_applications.py#L187
`tmpdir` in this test (and some others) has type of some `LocalPath`. This makes to throw exception here:
https://github.com/encode/starlette/blob/0c3a1e4a604a21bf615b0d9d93ad2070ff77edb7/tests/test_applications.py#L188
```
TypeError: join() argument must be str or bytes, not 'LocalPath'
```
and here:
https://github.com/encode/starlette/blob/0c3a1e4a604a21bf615b0d9d93ad2070ff77edb7/tests/test_applications.py#L193
```
TypeError: argument should be string, bytes or integer, not LocalPath
```

Hack `tmpdir = str(tmpdir)` on the top fixes it, but I don't understand where this variable is generated.

**Comment by em92** [comment]
Nevermind, overrode tmpdir using https://github.com/em92/starlette/commit/607e8a77a724717321533fc7b6b73996ec8f7563

**Comment by lovelydinosaur** [comment]
`@async_generator` <--- This is really neat!

**Comment by em92** [comment]
My python3.5 port is ready to use.
https://github.com/em92/starlette/tree/python35-port

Will update on every upstream version bump
