### ISSUE TITLE
How to get the app in a view?

### ISSUE THREAD

**Issue by ojii** [Kludex/starlette#226]
How do I get the current app in a view? Ideally `Request` would have an `app` property so the app object doesn't have to be a global.

**Comment by lovelydinosaur** [comment]
Any particular motivations to *not* just access the global app instance?

**Comment by ojii** [comment]
I don't like mutable globals, so my app I was building had no global app-object at all but rather builds the routes etc inside a function.

**Comment by lovelydinosaur** [comment]
Okay. I'm not convinced if we'll want to support a `request.app` or not. I'm a bit wary that it'd push us towards starting to tie everything everywhere onto the app instance. As it happens you *can* use `request['app']` right now, but it's not documented API and I wouldn't rely on it staying around.

Out of interest: Did you need the app instance in order to do `app.get_template(...)` or was there something else you wanted to introspect?

**Comment by ojii** [comment]
`get_template` was indeed what I wanted and I did find `request['app']` to achieve it. I also wanted to store my applications configuration object (which also holds DB connections etc) on it so it can be used in handlers, again without having to resort to global objects.
