### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by Serkan-devel** [Kludex/starlette#241]
I'm trying to use an ASGI app as a proxy as explained [here](https://github.com/kennethreitz/responder/issues/252). However, is might require something like [wsgiprox](https://github.com/webrecorder/wsgiprox) but for ASGI. Could there be proxy support on starlette?

**Comment by lovelydinosaur** [comment]
Yup, we'll certainly add a proxy component at some point.

You can take a look at https://github.com/encode/starlette/pull/24/files if you want a starting point on that.

**Comment by yvess** [comment]
I'm also interested in this

**Comment by lovelydinosaur** [comment]
Here's an example of an ASGI proxy app, that you could mount within Starlette... https://gist.github.com/tomchristie/5765e10a90a41c7e57470e2dc700f9db

**Comment by dhirschfeld** [comment]
Just found this issue after being pointed to the gist. The implementation there seems to work great for http requests but I'm struggling to adapt it to also work for websockets.

Anyway, it's very useful functionality as-is so it would be great to have this in `starlette` itself. :+1:

**Comment by dhirschfeld** [comment]
There is an implementation over at [`valohai/asgiproxy`](https://github.com/valohai/asgiproxy) but I'm actually using `trio` so can't use that directly.

Since the implementation here uses `httpx` which works with `trio` I can actually use that which is great! :heart:

For the websocket part I think I might have to cobble something together with [`trio-websocket`](https://github.com/HyperionGray/trio-websocket)

**Comment by lovelydinosaur** [comment]
Closing this off. If someone would like to develop a proxy app based on Starlette that'd be great. No particular reason it'd need to be in the core package tho.
