### ISSUE TITLE
Support for NoSQL databases

### ISSUE THREAD

**Issue by Midnighter** [Kludex/starlette#248]
Kudos for merging support for a Postgres middleware and wanting to support MySQL and SQLite in future.

I was wondering if you see supporting other databases inside of starlette or if you'd rather have separate packages such as starlette-mongo-middleware, for example.

**Comment by lovelydinosaur** [comment]
Certainly as third-party packages yeah. Hopefully the DatabaseMiddleware will do a good job of demonstrating how to approach alternative backends.

Third party backends can populate "database" in the ASGI scope if they want, in order to allow `request.database`, or else populate some other bit of scope. For example populate `"mongo"` to get the more generic `request["mongo"]`.

Something else I think would be worth adding to the database documentation would be an example of using `DatabaseMiddleware` with a plain ASGI app, rather than a `Starlette()` application instance. That'd help make it more obvious that the DatabaseMiddleware can also work with other ASGI frameworks or with plain ASGI applications.
