### ISSUE TITLE
Creating a streaming (audio) response

### ISSUE THREAD

**Issue by Midnighter** [Kludex/starlette#268]
It took me a little while to get this right so I wonder if you can see this as an addition to the docs somewhere? In my case I am loading audio as bytes from a database and I create a response in the following way:

```python
from io import BytesIO

from starlette.endpoints import HTTPEndpoint
from starlette.requests import Request
from starlette.responses import StreamingResponse


class AudioEndpoint(HTTPEndpoint):
    async def get(self, request: Request) -> StreamingResponse:
        """Return an mp3 audio stream."""
        # Load the content from the database.
        audio = ...
        headers = {
            "Content-Length": str(len(audio))
        }
        return StreamingResponse(
            self.stream_audio(record), media_type="audio/mpeg3",
            headers=headers
        )

    @staticmethod
    async def stream_audio(record: bytes, chunk_size: int = 4096):
        with BytesIO(record) as stream:
            data = stream.read(chunk_size)
            while data:
                yield data
                data = stream.read(chunk_size)
```

Hints for improvements are, of course, welcome :wink:

**Comment by lovelydinosaur** [comment]
Thanks! I'm not sure that the example is sufficiently different from the existing `StreamingResponse` docs https://www.starlette.io/responses/#streamingresponse tho I'd be happy to conside documentation pull requests. Bit of a balance to strick here - your example is clearly a more realistic case that we could present, but the dumbed down text-streaming example can at least stand as a complete example on its own. Perhaps we ought to mention use cases such as streaming audio in the docs?

**Comment by Midnighter** [comment]
I think I was struggling a bit with the decision to send everything as one big chunk or whether to stream it. That's not really Starlette specific, though, so probably current docs are fine and maybe someone is happy to find this here on GitHub.

**Comment by lovelydinosaur** [comment]
You may also want to take a look at `FileResponse`, which deals with streaming files from disk.

**Comment by Midnighter** [comment]
I considered it but writing the content from the database into files seemed silly.

**Comment by lovelydinosaur** [comment]
Ah sure. No, don't do that. :)

**Comment by amias-channer** [comment]
This approach can work but it is quite dependent on the encoding of the audio files , most mp3 files will work for this , some wont, browser support for streaming different files like this is patchy (e.g. chrome supports wav, nobody else does) . Really you should be writing the correct headers in the audio stream for streaming and content length if you want this to work reliably.  If you want to do this seriously its better to use websockets and a javascript client where you don't have to keep pretending to be serving webpages. I would avoid putting this in the documentation because its likely to generate a lot of confusing answers.
