### ISSUE TITLE
Breaking Change

### ISSUE THREAD

**Issue by JonGrrr** [Kludex/starlette#2803]
With the latest release on Dec 14, starlette is no longer being able to be pulled automatically using pip install commands.   It's getting a hash key mismatch.   Can someone look into this?

**Comment by Kludex** [comment]
I don't see anything wrong with it... What's the output you have?

**Comment by JonGrrr** [comment]
We're getting a hash mismatch error

**Comment by Kludex** [comment]
You need to help me to help you here. How can I reproduce? And what's the output?

**Comment by zanieb** [comment]
A hash mismatch error sounds like you have the wrong hash for the release in a requirements file?

Note when opening issues, it's best practice to share an example of the error you're encountering, the command you used, and any other information that can help maintainers reproduce it. Otherwise, we can't help.

**Comment by Kludex** [comment]
Closing as stale.
