### ISSUE TITLE
Websockets: json as text instead of bytes

### ISSUE THREAD

**Issue by JoseKilo** [Kludex/starlette#332]
Starlette uses bytes to send/receive json (instead of text). Is there a reason for this?

Text sounds more natural, since python's json module returns `str`.

Aiohttp for example uses text: https://github.com/aio-libs/aiohttp/blob/94e7b49e26f0e7cb4b7823764066fa7a62b09200/aiohttp/web_ws.py#L294-L296 

I couldn't find any standard that specifies this.

JS libraries don't seem to implement any json interface, but people usually do `JSON.parse(...)` which would fail in this case (depending on the environment).

**Comment by lovelydinosaur** [comment]
See also: #316

JSON is specified as a *binary* protocol, that is utf-8 encoded. (Rather than a text protocol, that can be encoded into one of several different binary encodings)

However, the most popular standard libraries don't tend to get this right (including Python, and JavaScript), so pragmatically, we may change this around. We'll need to figure out how best to do this without breaking any backwards compatability, and probably also ensure that it is configurable.

**Comment by JoseKilo** [comment]
Oops, I missed that PR. Thank you for clarifying !
