### ISSUE TITLE
get enpoint in middleware

### ISSUE THREAD

**Issue by jgirardet** [Kludex/starlette#365]
Hi,
Sorry to post a question here but I don't know where to ask it.

I'm doing a middleware which has to behave different depending endpoint view is function or coroutine.

How could I retrieve the handler name from the url   (or from anythig else)?

thanks

**Comment by lovelydinosaur** [comment]
So, ASGI middleware occurs * before* routing.

* Server -> Middleware -> Router -> Endpoint

You *can* either:

* Write a decorator.
* Write middleware that alters the *response* depending on what the endpoint was. ("endpoint" will be set in the scope at that point).

> I'm doing a middleware which has to behave different depending endpoint view is function or coroutine.

What are you trying to do, exactly?

**Comment by jgirardet** [comment]
This an integration for pony orm. it's still very alpha middleware. according some tweaking to pony being discussed with pony's author

```
class PonyASGI:
    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    def __call__(self, scope: Scope) -> ASGIInstance:
        if scope["type"] == "http":
            return functools.partial(self.asgi, scope=scope)
        return self.app(scope)

    async def asgi(self, receive: Receive, send: Send, scope: Scope) -> None:)
        self.inner = self.app(scope)
        await db_session(self.inner)(receive, send)

```
pony handles transaction in his db_session decorator which support both function and coroutine (still a small bug but quite good)
The idea is to not wrap every view in decorator but to have some middleware to decorate each view.
This example is working with coroutine but fails with regular function. I need to to have different behaviour for standard function.

**Comment by lovelydinosaur** [comment]
> This example is working with coroutine but fails with regular function. I need to to have different behaviour for standard function.

Middleware wraps other ASGI applications, so `self.inner` here is *always* an `async` function. If you've got a syncronous callable at that point, then you're doing something wrong.

PonyORM is a standard threading-concurrancy ORM, rather than an async ORM (okay, the session can wrap a coroutine, but the operations themselves are not async). This means that if you're using it with Starlette, then you want to make sure that any operation that runs against the database gets run within a threadpool, off the main asyncio loop.

The simplest way to get things right is *just to use sync views* with Starlette, and use PonyORM's context manager to *explictly* wrap up transactions within the views.

```python
@app.route('/my_view')
def my_view(request):
    ...
    with db_session:
        u = User.get(username=username)
        ...
```

I've had a bit of a browse - it's not obvious to me exactly what the session decorator does differently when applied to a coroutine, but I don't believe that the operations are actually non-blocking there (it probably works properly with generator functions, and *happens* to not break loadly with async functions but *actually* blocks the async loop.) Short version: Just use sync views and explicit sessions within them if you want to use Pony with Starlette.

(In *any* case middle-needs-to-know-the-endpoint wouldn't be what you actually need.)

**Comment by nhumrich** [comment]
Sorry to re-open this question. I have a similar ask. 
I am currently working on an authentication middlewear. The problem is that I have some routes that can be unauthenticated, and others that require authentication. 

Without being able to get the handler from the middleware, the only other option I can think of is building my own router to route the path, essentially do some regex matching for every route that can be unauthenticated, which is less then ideal.

Any thoughts on being able to ask the router which handler would handle a specific route? I see there is a method for doing the opposite (getting the path for existing handlers)

@tomchristie

**Comment by em92** [comment]
> The problem is that I have some routes that can be unauthenticated, and others that require authentication.

Instead of middleware, try to make different endpoint classes, derived from [HTTPEndpoint](https://www.starlette.io/endpoints/). One endpoint requires auth, the other one - does not.

**Comment by lovelydinosaur** [comment]
We'll likely have a look at finessing this sometime reasonably soon, but the answer is essentially...

Use `AuthenticationMiddleware` to perform the auth itself, and `@requires` to limit the permissions.

https://www.starlette.io/authentication/
