### ISSUE TITLE
Combining mountpoints

### ISSUE THREAD

**Issue by em92** [Kludex/starlette#380]
We have:
```python
# new_app.py
from starlette.applications import Starlette
from starlette.responses import PlainTextResponse

app = Starlette()

@app.route('/method1')
async def homepage(request):
    return PlainTextResponse("method1")
```

```python
# old_app.py
from flask import Flask
app = Flask(__name__)

@app.route("/method2")
def hello():
    return "method2"
```

```python
# main.py
from starlette.applications import Starlette
from starlette.responses import PlainTextResponse
from starlette.middleware.wsgi import WSGIMiddleware

import uvicorn

from old_app import app as old_app
from new_app import app as new_app

app = Starlette()
app.debug = True

app.mount("", new_app)
app.mount("", WSGIMiddleware(old_app.wsgi_app))

if __name__ == '__main__':
    uvicorn.run(app, host='0.0.0.0', port=8000)
```

In current implementation:
- /method1 returns "method1"
- /method2 returns 404 error

If we change order of mounts like this:
```
app.mount("", WSGIMiddleware(old_app.wsgi_app))
app.mount("", new_app)
```

- /method1 returns 404 error
- /method2 returns "method2"

How to make /method1 and /method2 both to work?

**Comment by tihomirptotev** [comment]
Hi,
I think you should specify a mount point for the flask app, like this:
app.mount("/flask", WSGIMiddleware(old_app.wsgi_app))

**Comment by em92** [comment]
Thanks for tip, @tihomirptotev 

But example above is based on use-case of continuous migrating from flask to starlette, while leaving urls in app the same.

**Comment by lovelydinosaur** [comment]
Mounted routes matches are evaluted eagerly - if it matches the prefix, then it *will* be dispatch to that mounted application.

There's no good general purpose way to resolve this, since the mountpoint can be any ASGI application, and we can't determine if it's a 404 without *actually* dispatching the request to the application.

The best you could do here, is to *explicitly* include the new routes rather than mount them, and then have the catch-all `app.mount("", WSGIMiddleware(old_app.wsgi_app))` as your last registered route.
