### ISSUE TITLE
Events (signals) dispatcher

### ISSUE THREAD

**Issue by alex-oleshkevich** [Kludex/starlette#454]
Event Dispatcher

## Motivation
Events (signals) is a common utility in a modern frameworks.
They let your application to react on various events triggered within request/application lifecycle.
Also, this is a good instrument for a 3rd-party plugin developers.

## RFC
In this RFC I propose to add `EventDispatcher` class to manage events.
This is a class with the following API:
```python
class EventDispatcher:
    def subscribe(self, event_class, listener_callable)
    def unsubscribe(self, event_class, listener_callable)
    def unsubscribe_all(self, event_class)
    async def trigger(event_instance)
```

The `trigger` method is asynchronous due to listeners may access files or read the database. 

The `event` is an arbitrary class instance. 

### Usage
```python
def on_app_start(event):
    print('app started')

class AppStarted:
    def __init__(self, app)
        self.app = app

app = Starlette()
events = EventDispatcher()
events.subscribe(AppStarted, on_app_start)

# this may live in starlette's app and fired in lifespan hooks
await events.trigger(AppStarted(app))
```

### Extras
As a part of this, Starlette may provide these events out of the box:
`AppStarted` - lifespan start
`AppFinished` - lifespan shutdown
`HTTPRequestStarted`, `HTTPRequestFinished`, `HTTPRequestErrored`, `WebsocketConnected`, `WebsocketDisconnected`

If it works, I will submit a PR.

**Comment by lovelydinosaur** [comment]
So, we have server lifespan events - startup & shutdown. https://www.starlette.io/events/
Middleware can be used to hook into other cases. Sticking with ASGI middleware is preferable, because the call chain ends up being more obvious, plus the middleware will be usable with other ASGI frameworks.

Usage of signals in Django is generally a pain maintenance-wise because it's too indirect and non-obvious. I'd prefer we don't go down this route.
