### ISSUE TITLE
Use "308 Permanent Redirect" for redirect slashes behavior.

### ISSUE THREAD

**Issue by tibudiyanto** [Kludex/starlette#464]
Hi,
I stumbled upon a quirk in starlette that is not properly documented. It seems like all of my HTTP request to a route without trailing slash are being redirected to route with trailing slashes. Say I am hitting `http://hostname/mountpoint/api` it will be redirected (302) to `http://hostname/mountpoint/api/`. This messed up your api calls; if you call POST to `http://hostname/mountpoint/api` it will be redirected to GET `http://hostname/mountpoint/api/`.

I dig on the source and see this redirect_slashes flag and setting it to False fix this. I feel this behavior (the auto redirection) should be documented.

**Comment by alex-oleshkevich** [comment]
Alternatively it can raise an exception like Django does.

**Comment by hjkelly** [comment]
I'm new to fastapi, and I think I'm running into this issue as well. If I forget a necessary slash, I'm redirected, which has no side effects for `GET`, but `POST` loses its data and is changed to a `GET`.

I'm new to this tool, but I've used Django for a decade, as well as django-rest-framework. Django's `APPEND_SLASH=True` breaks non-`GET` requests. django-rest-framework provides routers for their viewsets, but you have to override the `__init__` method to make trailing slashes optional. Even then, `@action` subresources must have trailing slashes. In my opinion, that functionality has always seemed broken.

Instead of modifying the docs to clarify this, what if the routes were forgiving of slash confusion? Instead of 404ing or even redirecting, `compile_path` could just ensure there's a `/?` instead of `/` or no slash at all. I suggest this because I've made incorrectly-slashed requests hundreds of times over the years, and doing this with POST requests can result in confusion or even lost data. In contrast, it seems unlikely that someone would miss the ability to specify routes _only_ with trailing slashes, or _only when there is no trailing slash.

Let me know what you think or if I can help.

**Comment by lovelydinosaur** [comment]
Right, then we're using the wrong redirect status code. 308 preserves the method.

**Comment by haizaar** [comment]
It sounds like a good idea to be able to configure Starlette to be trailing-slash-agnostic in one way or the other. Particularly after I just [wasted](https://github.com/tiangolo/fastapi/issues/244#issuecomment-494840792) several hours on trailing-slash issue :)

**Comment by tibudiyanto** [comment]
I think changing to 308 is the best solution. Will put up a PR if I got the time.

**Comment by lovelydinosaur** [comment]
@tibudiyanto Absolutely agreed. No particular need for us to allow it to be configurable either - it's clearly the wrong code as it stands.
