### ISSUE TITLE
Store single request object in scope

### ISSUE THREAD

**Issue by blueyed** [Kludex/starlette#497]
I've thought about doing so with regard to the templating, so that it does not have to be passed in via `context`, but https://github.com/encode/starlette/issues/495 looks like it would also help fixing state in this regard.

For templating it would be about saving the request there, and this could then be used instead of creating new objects then.

**Comment by lovelydinosaur** [comment]
Storing a request inside the scope isn't ever a useful thing to do, because the scope itself gives us everything that we need in order to instantiate a request instance.

If we have the scope available then we can always just do `request = Request(scope=scope)`

A good way to think of this is that the scope *is the state itself*, and that a Request instance is *an interface onto that state*.

**Comment by blueyed** [comment]
I see, and it makes sense.

But aside from added overhead (creating an instance several times per request), it requires to store global state for a request then in the scope (for https://github.com/encode/starlette/issues/495).

I've seen it more like `scope` is the initial state, and then it gets turned into a `Request` for http, which knows about `body`, while other connection types use different classes/interfaces.

**Comment by blueyed** [comment]
@tomchristie 
Any feedback on my previous comment?

I've noticed this to be a problem again with `request.state`, where it would create new State objects for "new" Request objects (created via middleware and app for the same scope).

I am using a lazy property on State (via descriptor), and it would be good to have it only being created once really then.  The workaround is to store/cache it on the `request.state` dict additionally.

**Comment by basepi** [comment]
Can we revisit this discussion? @dmontagu hits the nail on the head -- if we want to be able to create the `Request` from the scope, we need to propagate cached state like `request._body`. Otherwise, you hit issues like #495. In our Elastic APM middleware I've had to preemptively make sure we use the workaround in https://github.com/encode/starlette/issues/495#issuecomment-513138055 during the pre-request stage so that everyone can access the body who needs to.
