### ISSUE TITLE
Use LRU cache?

### ISSUE THREAD

**Issue by blueyed** [Kludex/starlette#501]
Stepping with a debugger into/through `Request.url_for` (used with templates) shows that it does a lot of `try/catch`, and processing in general.

I think it would make sense to use `functools.lru_cache` with it.

Is this out of scope for Starlette itself, and should apps do their own caching instead?

**Comment by lovelydinosaur** [comment]
Bit hard to say, since it depends on usage characteristics. (E.g. how much cache space you need for it in order to get decent enough hit rates)

I'm not neccessarily against us considering this at some future date, and *might* also consider it if someone wants to take a PR at it, but I don't think we should otherwise consider it as an open issue.
