### ISSUE TITLE
Helper to replace middlewear during tests

### ISSUE THREAD

**Issue by cjw296** [Kludex/starlette#522]
When you have middlewear that sets up a database session such as:

```
@app.middleware("http")
async def db_session_middleware(request: Request, call_next):
    request.state.db = Session()
    response = await call_next(request)
    request.state.db.close()
    return response
```

It's handy to be able to replace the middlewear for the duration of test, eg:

```
@pytest.fixture(scope='session', autouse=True)
def db():
    engine = create_engine(os.environ['TEST_DB_URL'])
    conn = engine.connect()
    transaction = conn.begin()
    try:
        session = Session(bind=conn)
        Base.metadata.create_all(bind=conn, checkfirst=False)

        async def testing_session(request: Request, call_next):
            request.state.db = session
            return await call_next(request)

        with replace_middleware_dispatch(
            app, db_session_middleware, testing_session
        ):
            yield session
    finally:
        transaction.rollback()
```

@tomchristie - would you welcome a PR that implements replace_middleware_dispatch?

If so, where should I put it in the package?

**Comment by lovelydinosaur** [comment]
Thanks for raising this.

It's not really the way around I'd approach things. I'd instead make sure that during test you flip the environment configuration so that you're not using different codepaths in the test case, you're just making sure that eg. the database connection URL is setup differently.

Eg. here https://www.starlette.io/config/#a-full-example we're setting `TESTING = True` in the `conftest.py` and then ensuring that we deal with the environment setup appropriately.

**Comment by cjw296** [comment]
Hmm, using the approach you suggest, how would you:
- run the database setup DDL inside a transaction
- run each test in its own subtransaction
?

The above is the fastest and most robust way I've found to test against databases, such as postgres, that support transactional DDL.

Put differently: with your suggested approach, how would you get side of data stored in the database by your tests?

**Comment by lovelydinosaur** [comment]
> run the database setup

The config docs have an example of how to gear up test database setup. You may want to adapt it so that it runs any migrations.

> run each test in its own subtransaction

For test isolation see eg. https://github.com/encode/databases#test-isolation
The docs in Starlette have something v. similar to that where they pass `rollback_on_shutdown=settings.TESTING` to the database middleware.

**Comment by cjw296** [comment]
So, I'm not using Databases, this is a FastAPI app so I can use the non-async SQLAlchemy ORM.

I'm surprised the `force_rollback=True` and `rollback_on_shutdown=settings.TESTING` approaches feel cleaner to you that just replacing the middlewear that sets up the session for the test :-/

**Comment by lovelydinosaur** [comment]
> So, I'm not using Databases, this is a FastAPI app so I can use the non-async SQLAlchemy ORM.

Sure - same applies. Personally I'd wrap it up in a middleware class that is parameterized by `database_url: str` and `test_isolation: bool`, or else at least switch between different middleware classes in the application config depending on the environment.

Keeping in line with config-through-environment rather than switching out to alternative implementations in the test suite is the most consistent approach for Starlette itself to take, tho I've no probs whatever with folks approaching their own stuff differently.

**Comment by cjw296** [comment]
How would I change which middlewear is used for a test run versus a production startup?

if I understand the example you link to above, it's predicated on `conftest.py` being executed before `myproject` is ever imported. Is that a documented behaviour of `pytest`? Feels like it might be an implementation detail that could change in the future...
