### ISSUE TITLE
Feature suggestion: option to turn off url quoting in RedirectResponse

### ISSUE THREAD

**Issue by seandavi** [Kludex/starlette#528]
I creating a signed URL from boto3 that is returned url encoded. It would be nice to be able to return that url directly without having starlette apply quoting again. On my end, it is an easy fix to unquote the URL before passing to `RedirectResponse`, but it took me a few minutes of searching to figure out why the presigned URL was not working.

**Comment by lovelydinosaur** [comment]
It sounds to me on first pass that we ought to *either* be doing one thing *or* the other. (Rather than making it configurable.)

Are you able to take a look at eg. what the behavior would be in Flask, Django, or some other framework with heavy usage, that will already have been exposed to any issues here?

Are you able to take a look at how eg. requests expects the location header to be wrt. URL quoting?

Are there any relevant specs in this area?

**Comment by lovelydinosaur** [comment]
Going to close this off at the moment, tho totally happy to reconsider if we get some actionable input demonstrating a difference in our redirect behavior vs. Flask, Django, or similar.
