### ISSUE TITLE
TestClient waits for background tasks

### ISSUE THREAD

**Issue by teskje** [Kludex/starlette#533]
Trying to write tests for my app based on Starlette, I noticed that queries I do against my API using `TestClient` take a long time to complete because the client waits for background tasks spawned on the server.

This behavior slows done my tests unnecessarily, since I don't care about the completion of those background tasks in most cases. Is there a way to disable it and make the `TestClient` behave like a normal client of the API?

**Comment by lovelydinosaur** [comment]
Not currently no.

We *could* possibly accept a PR allowing an early return once it's got the response. I'm not sure what we'd want to call that in the API, but essentially allow for: `Client(run_to_completion=False)`.

I think we have the right *default* behavior for this at the moment, since we'd have more unpredicatable behavior if we're cancelling the task once we've got the response.

You probably want to try to find a different way to work around this tho.

**Comment by szelenka** [comment]
Hi @tomchristie which part of the code would one look at to start messing with the functionality?

I have a similar use case where a client will call one of my endpoints to get a token, then use that token in a subsequent call to update an object on S3. Then there's a background task in the original endpoint the client called, to validate if they actually used the token we provided to update the object in S3.

It works, but when using the TestClient I cannot create a unittest for it (because the TestClient is waiting for the background_task to complete, but that will never complete successfully until the client uses the token from the first endpoint to perform a subsequent action).

**Comment by lovelydinosaur** [comment]
This is where the test client makes the ASGI request... https://github.com/encode/starlette/blob/master/starlette/testclient.py#L235

**Comment by lovelydinosaur** [comment]
Okay, so this has come up again, in #578.

A sensible thing to do in the meantime is probably to ensure you've got a `TESTING` environment variable eg. [see here](https://www.starlette.io/database/#test-isolation) and simply have your background tasks return without doing anything if `TESTING` is set.

**Comment by hidalgopl** [comment]
I'd like to implement this.
My initial idea was to check `TESTING` (or other, more specific, e.g. `BACKGROUND_TASKS_DISABLED`) env var here: https://github.com/encode/starlette/blob/master/starlette/responses.py#L130 and if it's set. don't run `self.background()`
Thoughts @tomchristie ?

**Comment by euri10** [comment]
> Trying to write tests for my app based on Starlette, I noticed that queries I do against my API using `TestClient` take a long time to complete because the client waits for background tasks spawned on the server.
> 
> This behavior slows done my tests unnecessarily, since I don't care about the completion of those background tasks in most cases. Is there a way to disable it and make the `TestClient` behave like a normal client of the API?

or you can mock your background tasks @ra-kete and check they've been called
if hey're async you can patch using CoroutineMock from asynctest package or wait 3.8

**Comment by thomasleveil** [comment]
Is there a way to mock `BackgroundTasks` ?

**Comment by euri10** [comment]
Yes, mock it like any other function.

I found that if it's a coroutine using the CoroutineMock from asynctest is
useful.

Little example here for the background coroutine mock,
https://gitlab.com/euri10/celeryasgimon/blob/master/backend/app/tests/test_service.py#L108

A normal mock for a non async background task is just above,
Hope it helps


Le dim. 29 sept. 2019 à 8:40 PM, Thomas LÉVEIL <notifications@github.com> a
écrit :

**Comment by scy** [comment]
Would there be a relatively easy way to

* still run the background task (i.e. not mock it away)
* make the `TestClient` request not wait for the background task to finish (i.e. return as soon as the HTTP response is complete) and
* not cancel the background task?

One of my endpoints starts an operation in the background that takes a few seconds to finish. During this time, additional calls to the same endpoint should result in an error. In other words: The endpoint is locked while the operation is running. I want to test that locking behavior by firing a second request while the background task is still running, but I can’t, since the first `TestClient` request will wait for the task to finish before returning.

I would be fine with `TestClient` instead waiting for background tasks before the whole test returns (e.g. on `TestClient` destruction), since my background task doesn’t run that long and it wouldn’t slow my test suite down too much.

**Comment by lovelydinosaur** [comment]
I don't think we want to change this behaviour, but we'd certainly consider any pull requests that document it.

The [pattern described here](https://github.com/encode/starlette/issues/533#issuecomment-511315549) is what I'd recommend if you don't want the background tests running in the testing context.
