### ISSUE TITLE
get_directories in staticfiles.py has bad asserts

### ISSUE THREAD

**Issue by vinhquevu** [Kludex/starlette#534]
I don't think you can use F-Strings in assert statements.  I get "invalid syntax" if I try.

The line: 
`directory = os.path.normpath(os.path.join(spec.origin, "..", "statics"))`
Always assumes there is a folder `statics`?  I believe the standard is `static` and not `statics` and the user is not given the option to circumvent the step.  Does it make more sense to only include this step if `directory is None`.

The directory argument does not get the package path prepended, which I feel is implied in the documentation.

The `assert os.path.isdir(directory)` will fail every time since it will return the `__init__.py` of a package.

**Comment by dmontagu** [comment]
* I have no problem using f-strings in assert statements in python 3.7.3.
    * Tangentially related, it looks like the f is missing from the f-string asserts on [this line](https://github.com/encode/starlette/blob/master/starlette/staticfiles.py#L73) and [this line](https://github.com/encode/starlette/blob/master/starlette/staticfiles.py#L77).
* I personally would agree that it feels a little weird to look for `"statics"` vs. `"static"`. The examples from the staticfiles docs all use the folder name `"static"`, rather than `"statics"` (though they aren't using the packages option to specify the folder). But it's not a big deal to me. Maybe there's a reason for it? (E.g., it could be a breaking change at this point?)
* The docs [here](https://www.starlette.io/staticfiles/) say
> directory - A string denoting a directory path.

I personally don't think this implies any package's path would be prepended -- if it was, what package's path would you even expect it to be?
* I take it you are referring to [this line](https://github.com/encode/starlette/blob/master/starlette/staticfiles.py#L75) when you say the `os.path.isdir(directory)` will fail every time. But I don't think that's right -- the `".."` argument to `os.path.join` ensures you get the parent folder. (I verified that line does not cause any errors for me, and correctly gets the `"statics"` directory's full path.)

**Comment by vinhquevu** [comment]
The f-string failure I thought was strange and could be an issue in my python env, I'm using a debian build, 3.6.

The docs read this:
> The packages option can be used to include "static" directories contained within a python package. The Python "bootstrap4" package is an example of this.
> 
> ```
> from starlette.routing import Router, Mount
> from starlette.staticfiles import StaticFiles
> 
> app = Router(routes=[
>      Mount('/static', app=StaticFiles(directory='static', packages=['bootstrap4']), name="static"),
> ])
> ```
So a few things that I was wrong about, the docs do state clearly it's going to force looking for a static folder.  I agree that's the standard, but perhaps a feature request to make that less stringent.  However, "statics" would not agree with the docs. 
Perhaps the docs would be more clear if it read:

> The packages option can be used to include the "static" directory contained within a python package.

But that's getting really nit-picky. :)

Also, since the assert error message is identical in two spots I was testing the wrong location.  I agree the ".." will remove the reference to `__init__.py`.

The relation of package and directory is personally confusing to me, perhaps because the arguments work exclusively instead of in concert, but that's an opinion not a bug.

**Comment by lovelydinosaur** [comment]
So, question one would be "do we think `static` or `statics` is a better default for the packages?"

I don't recall what Django does there with `INSTALLED_APPS`, but we should probably follow the same style.

The other part of that is just about doing a decent job on the documentation (making it clear what `directory` does, and what `packages` does).

**Comment by dmontagu** [comment]
@tomchristie [this page of the Django docs](https://docs.djangoproject.com/en/2.2/ref/contrib/staticfiles/) says:
> Files are searched by using the enabled finders. The default is to look in all locations defined in STATICFILES_DIRS and in the 'static' directory of apps specified by the INSTALLED_APPS setting.

I believe this is reflected in the code [here](https://github.com/django/django/blob/master/django/contrib/staticfiles/finders.py#L140).

**Comment by lovelydinosaur** [comment]
Closed via #535 and released as 0.12.3.

Happy to also resconsider our static dir naming, but let's treat that as a sperate issue if anyone wants to open it.
