### ISSUE TITLE
Add support for 102 Processing HTTP code

### ISSUE THREAD

**Issue by LKay** [Kludex/starlette#564]
As per [RFC2518](https://tools.ietf.org/html/rfc2518#section-10.1) there is `102` HTTP status code, namely `Processing` that should be used for notifying consumer that the request has not finished processing on the backend. Common case is to use such status for long polling or status confirm of asynchronously running tasks. 

Some other status codes from this RFC are already included and are usable with Starlette.

Currently when `102` status is provided in the `Response` object server hangs for a while and throws error being unable to process such response.

**Comment by lovelydinosaur** [comment]
At the moment I'd like to treat that as out of scope, since it's *significantly* different. The server has to send 102 first, and then later send a follow-up status code. There's a whole stack of server side stuff that'd also need to be able to handle that correctly, including the ASGI server, any HTTP routing components between the client and the server, and the client itself.

If someone's keen to see this then they'll first need to demonstrate a couple of things...

* Are browsers able to deal with 102 interim status codes? If an HTTP session sends a "102 Processing...200 OK Hello, world" sequence, then does the network inspector correctly identify it as a 200 response?
* Are clients able to deal with 102 interim status codes? Use CURL as a benchmark here. I'd strongly assume that urllib3/requests doesn't but confirmation would be interesting?
* Do common proxy and/or server implementations deal with the interim status code correctly?
