### ISSUE TITLE
Providing custom context to GraphQLApp

### ISSUE THREAD

**Issue by DrPyser** [Kludex/starlette#591]
Hi.

It would be useful to be able to inject values into the `context` provided to the graphql schema when using the `GraphQLApp`. It can be used to provide dependencies, for example.

Thanks!

**Comment by lovelydinosaur** [comment]
I'm not exactly sure what you mean here - can you provide an example?

The `request` is currently available, which means you have access to any per-request specific information you might need.

**Comment by Upgwades** [comment]
I know this is a few months old but I'd like to bump it as I ran up against the same limitation. I think the line in question is this [one](https://github.com/encode/starlette/blob/df0efb66030e188ef55b3b834cd0a19509b27928/starlette/graphql.py#L100). 
To give a real world example say I'd like to pass the sqlalchemy db session to my GraphQL resolver as context during an execute see this [graphene example](http://docs.graphene-python.org/projects/sqlalchemy/en/latest/tips/#querying) for what I'm talking about.
Access to execute's context is one example but there are other graphql functionalities that are implicitly disallowed at the moment due to restrictions on what can be passed to execute.

**Comment by DrPyser** [comment]
@Upgwades For a db session, you can set `request.state.session` in a http middleware. Then in the resolver you can access it as `info.context["request"].state.session`.

**Comment by brendanlong** [comment]
The frustrating thing about this is that it's possible but forces layering violations: I can't write a Graphene schema that isn't intimately aware of the web server that's going to be executing it :(

**Comment by DrPyser** [comment]
Yes, good point. @tomchristie could you consider reopening this?

**Comment by mjpolak** [comment]
Topic is outdated, but I'm facing same issue. Is there any solution for it now?
