### ISSUE TITLE
How to use scopes for auth?

### ISSUE THREAD

**Issue by jodusan** [Kludex/starlette#627]
I don't see any info on how to correctly use scopes, but everyone seems to know how it works since there are no questions. Can someone point in direction where I should look in order to understand the auth/token mechanism? 

Is it the same concept from some other framework under a different name? 

(I'd gladly send a PR with better docs, since currently it's super-basic docs)

Thanks

**Comment by dmontagu** [comment]
Starlette leaves it almost entirely to you to decide (and *implement*) how you want to perform authentication and handle scopes. This would be done by making a custom `AuthenticationBackend` and adding appropriately-configured `AuthenticationMiddleware` (as shown [in the docs](https://www.starlette.io/authentication/)).

It's not clear to me whether your question is more starlette-specific, or more about the concept of token+scopes-based authorization in general. In the second case, the [Auth0 docs](https://auth0.com/docs/scopes/current) may provide a good place to get your bearings.

Another example that dives a little more concretely into the mechanics of authorization would be the [FastAPI Security docs](https://fastapi.tiangolo.com/tutorial/security/first-steps/). **Note:** FastAPI does *not* make use of starlette's built-in approach to authorization, but may still be useful for seeing how authorization can work in practice (and, after all, FastAPI *is* built on top of starlette).

-------

It seems to me that your question was less specific-to-starlette and more about how to handle auth in general. However, if I have misinterpreted and your question really was more about the mechanics of how to implement a starlette `AuthenticationBackend`, it might help if you could clarify a little more what you have tried or what you are already familiar with.

**Comment by jodusan** [comment]
@dmontagu Thanks for the answer, I really appreciate it! 

1) You're right, I'm kinda looking for both. I'm aware of cookie based auth mechanism and http auth, and I was curious how is it implemented by starlette since cookies need to be stored somewhere on the server side too in order to verify the session. But I haven't configured any db related data for starlette sessions?

2) If I understand it correctly scopes boil down to a list of strings (or other ids) that define which parts of app you can access?

3) Not looking for 3rd party auth system. Just wondering how to do cookies based auth myself in starllete. Do I set them manually and should they be encrypted? (or is it already done)

**Comment by dmontagu** [comment]
@dulex123 

1. You are responsible for implementing the (server-side) session management yourself. In particular, if you want/need to store session-related data in your database, you'll need to handle that manually. I'm not sure if there are any good third party tools for this (though it sounds like you might be uninterested anyway).

2. Yes, that's right.

3. You are fully responsible for generating, storing, reading, and interpreting the cookies yourself; starlette just gives you some functions that make it easier to accomplish the storing and reading parts. Starlette will not handle any encryption or other similar security-oriented functionality for you.

    I'm not a security expert, but my understanding is that typically you wouldn't encrypt cookies; instead, you would just sign them to ensure they cannot be faked. (If for some reason you *did* want/need to include encrypted information in the cookies nothing is stopping you, but you'd still have to implement it yourself.)

    Two good choices for handling the signing: [itsdangerous](https://pythonhosted.org/itsdangerous/) and [pyjwt](https://github.com/jpadilla/pyjwt). I think similar functionality can be implemented using either one, but depending on your use case one may be better than the other (I'm not deeply familiar with either, but use pyjwt in my projects to implement (scoped) access/refresh tokens).

Note that whether you encrypt the token or not, you should *always* be using https when authorization credentials (token or otherwise) are being sent from a client to your server. Https is what prevents the cookie/token from being discovered by attackers, *not* encryption of the token. The only thing encrypting the token will do is hide the data from the authenticated user themselves (which is typically not necessary).

**Comment by jodusan** [comment]
@dmontagu Thanks a lot! This made it much more clear!
