### ISSUE TITLE
Use Exceptions rather than `assert` to handle WebSocket state violations

### ISSUE THREAD

**Issue by jeffbuttars** [Kludex/starlette#66]

**Comment by lovelydinosaur** [comment]
So, we've got a bunch of different places in the codebase where we use assertions to guard against stuff that'd explicitly be a programmer-error-case. I'd be totally okay with any pull requests dealing with changing *any* of these cases (including the WebSocket state ones), but I'm not otherwise going to consider it as an open issue.
