### ISSUE TITLE
Gunicorn Workers Hang And Memory Does Not Get Deallocated

### ISSUE THREAD

**Issue by MeteHanC** [Kludex/starlette#667]
Hey,

I'm currently running a load test. I'm serving my Starlette app with gunicorn, with this line of code ;

`gunicorn -w 48 -k uvicorn.workers.UvicornH11Worker -b 0.0.0.0:5000 app:app --timeout 10 --threads 2`

So there is nothing wrong with the performance but the thing is memory consumption gets increased continuously. Even after the test is finished and app is not receiving any more requests, memory does not get deallocated.  There was no request that app could not return a response not even an error. Could this be related to uvicorn workers?

**Comment by wanaryytel** [comment]
Related fastapi issue here: https://github.com/tiangolo/fastapi/issues/596

**Comment by lovelydinosaur** [comment]
Generally when I've seen any issue along these lines come up, the end result *tends* to come out as "this is just the Python runtime pre-emptively hanging onto memory that's been allocated, rather than returning it to the O/S" rather than a memory leak. Eg. https://stackoverflow.com/questions/15455048/releasing-memory-in-python.

That may or may not be the case here, but it's worth keeping in mind.

Having said that, your comment of "This continues until I run out of memory or restart the process." *does* sound suspect.

The way to approach this would be:

* Try running under at least two of hypercorn/daphne/uvicorn to isolate if it replicates under different servers. If it does replicate under different servers, then it's probably not a server issue.
* Reduce the issue to the *simplest* possible reproducing case you can - ideally just a starlette app with a single endpoint. Keep trying to remove code and simplify until you've got the simplest possible case you can come up with.

**Comment by MeteHanC** [comment]
> 
> The way to approach this would be:
> 
> * Try running under at least two of hypercorn/daphne/uvicorn to isolate if it replicates under different servers. If it does replicate under different servers, then it's probably not a server issue.
> * Reduce the issue to the _simplest_ possible reproducing case you can - ideally just a starlette app with a single endpoint. Keep trying to remove code and simplify until you've got the simplest possible case you can come up with.

Actually, I have followed the same steps. I figured out that it is a multiprocessing Pool issue, even with closing the pool, under the high load, somehow pool workers could not be disposed.


> Generally when I've seen any issue along these lines come up, the end result _tends_ to come out as "this is just the Python runtime pre-emptively hanging onto memory that's been allocated, rather than returning it to the O/S" rather than a memory leak. Eg. https://stackoverflow.com/questions/15455048/releasing-memory-in-python.

And after continuing without multiprocessing pool, I've encountered this. Though it did not cause a run-out-of-memory situation, it still consumed some memory under high load, did not release it but under another high load test, memory usage did not increase linearly. I think this is what you meant when you said '

> ..hanging onto memory that's been allocated


I think this answer cleared it up for me. But since there are more people struggling about this, I will leave 'closing the issue' to repo owners . Thanks a lot for the response!

**Comment by lovelydinosaur** [comment]
It's not clear to me what resolution you came to *exactly*.

Is there an core issue with Python's `loop.run_in_executor` implementation, or were you doing something with multiprocessing that was causing the issue?

Is there a simple example case that reproduces the issue, and can actually crash the interpreter?

**Comment by MeteHanC** [comment]
So, I was using multiprocessing.dummy's pool with map function in some of the functions. (Btw I am talking about a load test which makes around 30K requests per minute, single server) 

So dummy processes(threads) spawned by multiprocessing.dummy library could not be disposed even if I kill the main process (gunicorn process in this case). 

I will try to reproduce the issue with appropriate parameters when I can and let you know about it.

**Comment by gvbgduh** [comment]
@MeteHanC you might be creating too many workers for gunicorn, the best practices say the number of workers is a number of CPU cores + 1 [link](http://docs.gunicorn.org/en/stable/design.html#how-many-workers), but in practice, it'll highly depend on your application and memory usage. If you're keeping in memory big amount of data it'll start choking much sooner (like you have billion items lists or loading big files in memory).

`multiprocessing.dummy` is a wrapper around multithreading that are green threads where the GIL is presented. Although, spawning new processes (not to confuse with multithreading) may drive your memory consumption even crazier as it allocates its own memory stack and another OS process, while gunicorn is already running an estimated amount of processes.
So, instead of `multiprocessing.dummy` you might have better success with `asyncio` features (i have a small gist with some examples - https://gist.github.com/gvbgduh/fb189d9dffe322fe0f6f4fdd8d5f700f).
You can also have a look at the `ProcessPoolExecutor` for CPU bound tasks.

It might have different flavors depending on your environment, be it bare-metal beefy server or some instances in the cloud.
But, ideally, it would be great to profile the single process independently for an understanding of your memory needs and performance.

Sometimes the only way is to move it to chunks and/or external workers/pipelines/jobs, but I'm not fully aware of your context.

**Comment by lovelydinosaur** [comment]
That doesn't sound like the right approach. You'll have multiple worker processes "gunicorn -w 48", each capable of running 1000's of concurrent async tasks.

What you don't want to *then* do on top of that is have each async task start spawning multiple processes - you shouldn't need to be doing that. Having endpoints start forking threads or delegating to multiprocessing isn't a pattern you want to be reaching for.

**Comment by Gavin-Evans** [comment]
![image](https://user-images.githubusercontent.com/47597201/158041113-35d878c8-fe87-4ee4-9072-e902154f7b30.png)


Fortunately, I also encountered a similar problem, I don't understand it, how did you solve it?
