### ISSUE TITLE
Feature Request - Empty query string flags

### ISSUE THREAD

**Issue by GlennS** [Kludex/starlette#670]
HTTP URIs are allowed to have query strings without any values in them, like `/some-url?flag`. I'll call these 'flags'.

Starlette doesn't appear to provide a way to distinguish between these and not passing the flag at all, so `/some-url?flag` looks identical to `/some-url`.

I was redirected here after submitting this issue to FastAPI: https://github.com/tiangolo/fastapi/issues/610

I can work around it by making my clients pass `/some-url?flag=true` instead, so if it's a deliberate design decision not to support this then I understand.

**Comment by jodusan** [comment]
https://stackoverflow.com/questions/4557387/is-a-url-query-parameter-valid-if-it-has-no-value 

It should be a valid string?

**Comment by gvbgduh** [comment]
@GlennS what goal are you trying to achieve?
And how would you expect it to be passed to the `request.query_params`?
As it's currently parsed as a dict.

**Comment by jodusan** [comment]
@gvbgduh web standard that some API's rely onto is to retrieve length of each parameter. If no parameter value is passed you need to return length 0. But if you don't even get the parameter you cannot retrieve zero value for its length (since you didn't get the parameter in the first place). 

Check this PR: https://github.com/encode/starlette/pull/672/files

parse_qsl even has the parameter in place already it just needs to be enabled.
