### ISSUE TITLE
How to deploy starlette in production? 

### ISSUE THREAD

**Issue by blueray453** [Kludex/starlette#671]
I searched the documentation but could not find How to deploy starlette in production. Please help.

**Comment by trim21** [comment]
search `uvicorn`

**Comment by blueray453** [comment]
Does it need Apache or Nginx?

**Comment by trim21** [comment]
Have you ever used `gunicorn` for a web app?

Nginx -> gunicorn -> unicorn -> you starlette app

**Comment by trim21** [comment]
You can use nginx as proxy or simply expose gunicorn port to user.

**Comment by blueray453** [comment]
Thanks

**Comment by blueray453** [comment]
Sorry, I have one more question. Can I use starlette with Hypercorn?

**Comment by trim21** [comment]
I think you can... 
Both of them are based on asgi protocol.
(But I never used hypercorn, unicorn document says it's an alternative of unicorn)

>ASGI frameworks
>You can use Uvicorn, Daphne, or Hypercorn to run any ASGI framework.

**Comment by blueray453** [comment]
Thanks

**Comment by mangelozzi** [comment]
I read that Starlette is built on Uvicorn, does mean we can go nginx -> Starlette? Uvicorn is an ASGI server so then is Starlette is an ASGI server too?

**Comment by gnat** [comment]
Unfortunately this is a bit convoluted right now because `uvicorn` hasn't seen any real development for awhile.

* nginx/caddy/whatever (forward proxy) :arrow_right: gunicorn (worker management)  :arrow_right: uvicorn (workers) :arrow_right:  starlette (asgi app)

In the future we may see this simplified to one of:

* nginx/caddy/whatever (forward proxy) :arrow_right: uvicorn (worker management) :arrow_right:  starlette (asgi app)
* nginx/caddy/whatever (forward proxy) :arrow_right: sanic server (worker management) :arrow_right:  starlette (asgi app)

**Comment by Kludex** [comment]
> Unfortunately this is a bit convoluted right now because uvicorn hasn't seen any real development for awhile.

What do you need?

Edit: you mean the process manager on uvicorn?

**Comment by gnat** [comment]
> Edit: you mean the process manager on uvicorn?

That would be my number 1.

This does NOT even have to be on-par with sanic server, which adds a ton of other value: graceful shutdown of workers, various anti-ddos options, stats, etc. All of this stuff is nice but doesn't matter.

Just enough to remove gunicorn from everyones deployments would be amazing, see: https://github.com/encode/uvicorn/issues/517

**Comment by adriangb** [comment]
I can see the value in that stuff for some deployment topologies but keep in mind that plenty of people are deploying onto k8s, Cloud Run or similar things where there is already a process manager and two layers of process managers tends to be terrible.

**Comment by gnat** [comment]
Explain how k8s eliminates the need for gunicorn and uvicorn at this point in time? k8s is still the same topology, just without the forward proxy in the same container, aka:

gunicorn (worker management)  :arrow_right: uvicorn (workers) :arrow_right:  starlette (asgi app)

Same story with any container (Docker, podman), which was the original technology in the issue linked.

**Comment by adriangb** [comment]
You get rid of gunicorn and uvicorn workers and run `k8s -> uvicorn (no workers) -> asgi app`. Kubernetes _is_ a process manager, it can handle starting replacements for pods that crash, etc. It's kind of the whole point of it.

So it has nothing to do with containers, more to do with the fact that Kubernetes is ~ a process manager.

**Comment by trim21** [comment]
in k8s/docker usecase you don't start one container with multiple workers, you start multiple container, each container contain one worker.

 If worker is dead then container runner will start a new one.

unless you deploy docker container to single node, in that case you maybe still need gunicorn to start multiple container, or use reverse proxy like traefik/nginx with multiple container and rolling upgrade to achieve zero downtime upgrading.

**Comment by gnat** [comment]
Fair enough, that's a reasonable pattern for people deploying k8s.

Still, we're just exchanging deployment complexity for other deployment complexity at that point.

**Comment by trim21** [comment]
> we're just exchanging deployment complexity for other deployment complexity at that point.

Yes, and that's the point. 

All deployment complexity is in k8s/docker stack layer, so whatever the web tech stack you are using, you gain same deployment flow and same deployment result.

If someday you start a new wsgi server or a new website using golang, you can just pack it into container and reuse same deploy flow, without concerning about "that tool should I use to replae univorn to achieve this feature like graceful shutdown'"?

**Comment by adriangb** [comment]
I don't think anyone is saying to trade one for the other or that one is preferable to the other. Certainly k8s is complex, I wouldn't say it's a drop in replacement for Gunicorn.

My point was that not every deployment _needs_ Uvicorn to be a process manager and that Uvicorn should keep that in mind when iterating on those features, the docs, etc. Gunicorn for example forces the process management aspect onto you both in implementation, docs, etc.

**Comment by euri10** [comment]
having spent a while ago a fair amount of time on uvicorn's "process" capabilities, reloader, signals, etc, the biggest pain point for having more features on that topic is the too broad support uvicorn offers os-wise.

as long as Windows has to be supported it will be I think this way.

Also, I always have been very dubious about the recommandation by FastAPI on using gunicorn: it introduces an unecessary level of complexity, make prod debugging tedious and feels more like a dick contest on how to make the most request/s by using more procs. Add to that the fact that the gunicorn / uvicorn integration is barely tested, I would never use it in prod.

in my ideal world, uvicorn should be linux only and just offer reload support for DX, period. the ops side of things should be delegated to software that specialize in that, and in that only.

**Comment by Kludex** [comment]
If I didn't need approvals, I would have this feature on uvicorn. This topic has been discussed many times already, and the thing is that I don't even think it makes the code source more complex.

This discussion about K8s doesn't really matter, it's a fact that people use gunicorn with uvicorn, and the "way" to deploy an application is subjective. It's easier to deploy with gunicorn, and people will keep using it because uvicorn doesn't have it.

As @euri10 said, the integration with uvicorn is not tested, and honestly, the gunicorn test suite has a lot of mocks itself. 😬

There are two points about windows support:
1. signal treatment differs 
2. how to spawn processes, gunicorn uses fork, which is not supported by Windows

They are points to think about, but shouldn't be a blocking point to have this on uvicorn.

**Comment by gnat** [comment]
So I've been looking into the "1 worker = 1 container" pattern... 

I've replaced gunicorn with docker/podman itself for worker management (via `--scale` option and `deploy: replicas: ..`) to see how this performs using 16 and 32 "single worker" containers on Ubuntu 22.04 server (16 cores, 64 GB memory). .

It technically works...but the throughput is only about 70% of what I get with only 1 container of gunicorn managing the same number of workers.

Idle server CPU usage spikes from 5% (typical caddy/gunicorn/uvicorn) **up to 40% (!!)** due to what I assume is container overhead. :grimacing: it is a serious resource hog.

Kind of an insane price to pay for "worker management".

There are performance repercussions of leveraging your container orchestrator for this purpose.

**Comment by euri10** [comment]
very interesting, care to share the exact commands / setup @gnat ?

**Comment by gnat** [comment]
@euri10 Sure, here's the basic setup I'm using, should give you an idea of where I am at. You've got to plug in your own image/app, though (using `FROM ubuntu:22.04` here). To revert back to the higher performance single container setup:
* Remove `deploy: replicas: 32`
* Ports becomes `127.0.0.1:5000:5000`
* `command: uvicorn` is swapped with `command: gunicorn`
* Caddyfile just goes down to 1 backend (`127.0.0.1:5000`)

## Container orchestration

`compose.yml`

```yml
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --lifespan on --log-level warning --no-access-log  --proxy-headers --workers 1
    #command: gunicorn -k uvicorn.workers.UvicornWorker --worker-tmp-dir="/dev/shm/gunicorn" -c /app/gunicorn_config.py app:app
    restart: unless-stopped
    init: true
    # For 32 containers.
    ports:
      - "127.0.0.1:5000-5032:5000"
    volumes:
      - ./app:/app
    deploy:
      replicas: 32
    networks:
      - common

networks:
  common:
```

## Load balancer
`Caddyfile` (Ran using `./caddy run --watch`)

:warning: Fill in the remainder of the backends. Cut off for clarity.

```
{
  auto_https off
}

:80 {
  reverse_proxy 127.0.0.1:5000 127.0.0.1:5001 127.0.0.1:5002 ... {
    # Passive health.
    fail_duration 1s
    unhealthy_request_count 10000
  }
}
```

## Benchmarking

hey (https://github.com/rakyll/hey)

`./hey_linux_amd64 -z 10s -c 200 http://127.0.0.1`
`./hey_linux_amd64 -z 10s -c 500 http://127.0.0.1`
`./hey_linux_amd64 -z 10s -c 1000 http://127.0.0.1`

Also monitor system resources using `htop`

**Comment by adriangb** [comment]
First off I'll reiterate that no one is suggesting that you _need_ to run a specific topology. If I was running on bare metal then I agree it's probably best and easiest to use something like Gunicorn. The point is more for when you are already running on some sort of containerized platform with load balancing and container management capabilities, which is the case for a large number of deployments nowadays.

> It technically works...but the throughput is only about 70% of what I get with only 1 container of gunicorn managing the same number of workers.

I've seen the opposite: under high CPU bound load (think serving an ML model) I've gotten even better throughput from the "many single process containers" compared to the "few many process container" deployments. Here's an example repo that can be deployed on a reproducible cloud environment: https://github.com/adriangb/misc/tree/pycon-asgi. I got the following results:

```
gunicorn - io: 38.82 req/s, 1.84±0.38 s/req
uvicorn - io: 50.74 req/s, 1.72±0.29 s/req
gunicorn - cpu: 0.59 req/s, 149.79±73.84 s/req
uvicorn - cpu: 1.15 req/s, 76.01±28.57 s/req
```

This is obviously going to be very dependent on workload and other factors, I'm not saying that one thing is 2x faster than the other. But I think at least it's all in the same ballpark. That said if you asked me to explain why Uvicorn is 2x as fast as Gunicorn in that data (and remember that Uvicorn vs. Gunicorn is just a proxy for the deployment topology, the actual web server is not what we are testing here) I'd guess that it's the [thundering heard problem](https://uwsgi-docs.readthedocs.io/en/latest/articles/SerializingAccept.html) or other inefficiencies of how Gunicorn does load balancing.

> Idle server CPU usage spikes from 5% (typical caddy/gunicorn/uvicorn) up to 40% (!!) due to what I assume is container overhead.

I am surprised by such a big increase, but luckily (1) container platforms don't charge you for that, they charge you for the CPU cycles that _you_ use and (2) you should be autoscaling so that if your system is actually 95% idle you scale down.

I was able to reproduce my results with `hey` as well; neat little tool, thank you for linking it.
