### ISSUE TITLE
[QUESTION] Profiling calls to TestClient

### ISSUE THREAD

**Issue by nathanielobrown** [Kludex/starlette#686]
I'm having trouble profiling my FastAPI app when I use `starlette.testclient.TestClient`. The issue is that I get no visibility beyond the asyncronous calls to the test client (`<method 'control' of 'select.kqueue' objects>`), see attached image.

This seems like a generic problem with profiling async applications, but maybe the creators of the best async framework have some advice?

My typical workflow for profiling has been to make a test that's slow and then run it with `pytest --profile-svg` which generates something like this:

<img width="659" alt="Screen Shot 2019-10-23 at 6 35 23 AM" src="https://user-images.githubusercontent.com/5266576/67386454-04a4fe00-f563-11e9-949f-6cb9de8e8738.png">

What I'm used to with Flask/WSGI is I would be able to "see" into the API call and find how long the constituent parts took. My thoughts on possible solutions so far are:

1. Somehow run my app as WSGI for testing or in general. I'm not using FastAPI for async, I'm using it for ergonomics so losing async would not be a problem at this time
2. Use a different profiler that works with async (all I've found is django-silk)
3. Set profiling hooks inside of my API calls (not very attractive because it would be more work and potentially I'd have to check many different calls in one test to solve a slow test)
4. Maybe use a line profiler to find which API calls in my test are slow

How do you profile your Starlette/FastAPI/async applications? Is there anything I can do to make my existing workflow work, or another workflow I can adopt?

I love Starlette and FastAPI and am grateful for your work and any advice you might have.

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/686">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/686/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/686/pledge.svg">
</picture>
</a>

**Comment by dmontagu** [comment]
I'm also very interested in this. Given how the TestClient works, I think it might be hard to make profiling play nice with it (since it can take responsibility for server startup / shutdown, and starts/manages the async event loop in which the endpoint calls run). But maybe someone has figured out a good way to handle this.

It might also make sense to use a profiling middleware that you only add during test time? E.g. using `yappi`? If it were just a middleware it might be easy enough to apply, and in theory it could work with any asgi app. Obviously it would require more setup than just an extra argument to pytest though.

Something like this would be especially useful for looking for regressions and/or performance improvement opportunities while developing FastAPI itself, so I think it's definitely worth finding an answer. (Since starlette does less magic than FastAPI I think it stands to benefit less from improved performance introspection.)

**Comment by lovelydinosaur** [comment]
Maybe have a dig into what the `httpx` team have used, and see if there's anything useful there?... https://github.com/encode/httpx/tree/master/tools/httpxprof

It might also be worth trying `httpx.AsyncClient(app=app)` and seeing if you get more visibility when using that as a test client instead of Starlette's existing test client.

Would love to hear more on this thread about any progress you make!

**Comment by gvbgduh** [comment]
Very interesting indeed! I agree it might worth using the async client, so the TestClient isn't responsible for managing the event loop.

**Comment by nathanielobrown** [comment]
I tried out the `AsyncClient` and did not get more visibility. My technique was to create the client like this in my fixture
```
return AsyncClient(app=app, base_url="http://testserver")
```
and then use it like this (employing https://github.com/pytest-dev/pytest-asyncio)
```
@pytest.mark.asyncio
async def test_login_successful(api_client) -> None:
    resp = await api_client.get("/api/locations/")
    assert resp.status_code == 401
    assert "Not authenticated" in resp.text
```

The run time of the request still ended in call to `~:0:<method 'control' of 'select.kqueue' objects>`.

As an asyncio noob I don't know if there's something I should tweak here, but maybe I will check out `httpxprof`  when I have time. Also there enough API differences to httpx (adding await, change how `data` and `json` are passed) that I would have to do quite a bit of test fixing...

**Comment by dmontagu** [comment]
Here's a couple (related) issues that might be interesting to anyone following this thread:

https://github.com/tiangolo/fastapi/issues/701
https://github.com/sumerc/yappi/issues/21

I think the approach discussed in the FastAPI issue above is pretty close to being able to power an ASGI profiling middleware; the main outstanding issue is getting yappi to track the wall time of asyncio calls properly.

The creator of yappi thinks it might be possible to follow a similar approach to what was used to build the Greenlet profiler; I'll update here if we're able to make progress.
