### ISSUE TITLE
Is there some boilerplate structure of project?

### ISSUE THREAD

**Issue by jodusan** [Kludex/starlette#696]
Not sure on how to structure starlette project as many circular dependencies pop up. How should Database connection /  App creation / Endpoints(controllers?) / views be organized?

Anyones example could be helpful (im using gino as orm)

**Comment by lovelydinosaur** [comment]
These might be helpful:

* https://github.com/encode/starlette-example (templates & statics only)
* https://github.com/encode/hostedapi (a simple in-production app)

I'll be clearing up a bunch of this stuff as I work on `hostedapi`, since I'm partly using it to help thrash out better project structures, and clean out bits of starlette/uvicorn/databases/orm/typesystem/httpx that still need work before their APIs can reach 1.0.
