### ISSUE TITLE
[Feature] Add onegraph enhanced graphiql to included graphiql

### ISSUE THREAD

**Issue by seandavi** [Kludex/starlette#698]
See https://github.com/OneGraph/graphiql-explorer

For complicated schema, this addition to GraphiQL is a significant enhancement, particularly for discovery by third parties. 

![image](https://user-images.githubusercontent.com/92435/67812833-7b1b9180-fa76-11e9-8371-117e79607004.png)

**Comment by lovelydinosaur** [comment]
We could consider a pull request for this sure. Is there a generic mechanism for adding plugins to the igraphql explorer, and should we be looking at doing this in a more general way to let users pick and choose what extensions they want?
Related to this: I think we should *probably* consider pushing the GraphQL support into an independent third party app now, rather than having it in the Starlette repo itself. Anyone particularly keen in taking on maintainership if we decided to do that?

**Comment by seandavi** [comment]
I think a graphiql wrapper with config exposed from python would be a useful layer for a number of projects. As for graphql support, I agree that having it split out seems natural. I'm not claiming ownership here (time is limited, as for all of us), but I'll try to take a quick look to see how involved it is. 
I would be interested to hear how much usage/interest there is in the graphql tooling within the starlette community.

**Comment by lovelydinosaur** [comment]
Related: https://github.com/encode/starlette/issues/619

**Comment by JayH5** [comment]
Thank you for filing this issue. We have decided to deprecate GraphQL support within Starlette itself so I am going to close this issue. See #619.
