### ISSUE TITLE
Background tasks exception handler

### ISSUE THREAD

**Issue by aviramha** [Kludex/starlette#739]
Currently, if a background task faces an exception, it isn't handled and there's no way to handle it (rather than wrapping the task)
My suggestion is to be able to add exception handler for background tasks, as there is for requests.

**Comment by lovelydinosaur** [comment]
Yup, this is interesting.

So, the exception handler currently only runs for HTTP requests (not WebSocket) and only runs if a response hasn't already been returned. This is because any 500 page returned by the exception handler can't be displayed if we've already returned a response.

However, I think we've got the wrong policy there. Instead we ought to *always* run the exception handler, but only render its response if we haven't already started doing so.

The more tricky bit of that is how websockets should fit in there. I guess we probably want to change the signature from `handler(request, exc)` to `handler (conn, exc)`, and document that `conn` is an `HTTPConnection`, and might be *either one of* of the `Request` or `WebSocket` subclasses.

**Comment by aviramha** [comment]
Sounds good, should I submit a pr?

**Comment by lovelydinosaur** [comment]
Welcome to take a look at it, yup!

**Comment by aviramha** [comment]
I didn't quite understand the implications of the Websocket changes, as there's no defined signature (right now, besides http_exception func).

**Comment by aviramha** [comment]
Please check my PR, if it's OK I'll write tests and documentation.

**Comment by lovelydinosaur** [comment]
Also, just to get a slightly better idea of the context here - what kind of handled exception are you catching here, and what are you doing with it in the exception handler?

The default exception handling is setup so that you can decouple eg. "A page not found exception occured" from "here's how we want to render the 404 page".

When you're using background tasks you don't have anything to render, so it's a bit less clear what sort of use case *handled exceptions* have.

**Comment by aviramha** [comment]
The use case I'm after is Asgi Exception Middleware similar to Sentry.
I want to report all exceptions that happen in the service - including background tasks.
In my current project I'm using a decorator of try catch, instead of my default exception handler that works for request exceptions.

**Comment by lovelydinosaur** [comment]
Right, yeah. So, that's different, although we need some careful documentation around this.

Starlette has *exception handlers* for handling particular exception classes in a specfic way (eg. to raise a 404 Not Found, which isn't an error, but where you do want to bypass the standard flow), and an *error handler* for the last-ditch handling of all unexpected errors.

What you *actually* want here is for the *error handler* to always run...

https://github.com/encode/starlette/blob/master/starlette/middleware/errors.py#L158

**Comment by aviramha** [comment]
Oh, snap.
Did pretty much the same now for errors and created another PR #761 ..

**Comment by kevinvalk** [comment]
Definitely 👍 , this problem just bit me in the ass... currently exceptions in background tasks disappear which make for very interesting debugging sessions.
