### ISSUE TITLE
Back pressure?

### ISSUE THREAD

**Issue by pawamoy** [Kludex/starlette#802]
Hello!

I have opened [this issue about back pressure](https://github.com/tiangolo/fastapi/issues/857) on FastAPI, and @dmontagu agreed that it could be more interesting to discuss it on Starlette instead, so here it is 🙂 

I would like to know if thoughts were put in the design of Starlette to prevent, or help prevent system overloading due to lack of back pressure with async. Here is the direct link to the article https://lucumr.pocoo.org/2020/1/1/async-pressure/

I think @dmontagu gave a really good answer already, but maybe you (the authors, maintainers and users of Starlette) would like to share more about this! Thanks!

**Comment by lovelydinosaur** [comment]
So,

Network backpressure in both directions is handled by the ASGI server. For instance, Uvicorn deals with backpressure correctly on both the request and response bodies.

However network backpressure isn't actually the only thing we'd like to have in place here. We also want to ensure resource limiting at any potential bottlenecks. The most notable case here would be the number of available database connections.

Uvicorn currently allows you to set a `--limit-concurrency <int>` which hard-limits the maximum number of allowable tasks which may be running before 503's will be returned. In the most constrained case you could just set this based on the number of available database connections. Actually we *could* be doing better there, tho - it'd be nicer if uvicorn *queued* requests beyond that limit, and only responded with a 503 after a timeout period.

The other thing that we could do that'd be smart is defaulting timeout exceptions to 503 responses. So... supposing you've got a resource limit on:

* Acquiring database connections.
* Connection to the cache.
* Sending outgoing HTTP requests.
* Sending emails.

Those kinds of components always ought to have some kind of pool limiting available, and should raise timeouts if the resource cannot be acquired for a period of time. If Starlette is configured to map those exceptions onto 503 responses, then you'll get graceful failure behavior when a server is overloaded. We don't actually strictly need to do anything anything in Starlette there, since it already supports mapping exception classes to different error codes, but it might(?) be sensible to eg. nudge async packages into subclassing Python's built-in `TimeoutError` for resource timeouts, so that we could ensure there's a consistent base class which we can map to 503.

**Comment by pawamoy** [comment]
This is very interesting, thank you for this detailed answer. Maybe it would deserve a section in the docs (uvicorn/starlette/fastapi) once we have reports on such experimentations. I'd love to know how others handle this 🙂

**Comment by pawamoy** [comment]
I think we can close this now :slightly_smiling_face:
