### ISSUE TITLE
Mount requires trailing '/', while Route does not.

### ISSUE THREAD

**Issue by jwtrhs** [Kludex/starlette#823]
Mounted subroutes require the trailing `/` to hit their 'root' subroute, whereas regular `Route`s do not.

E.g.

```python
from starlette.applications import Starlette
from starlette.requests import Request
from starlette.responses import PlainTextResponse
from starlette.routing import Mount, Route

async def homepage(request):
    return PlainTextResponse('homepage')

async def subroute(request):
    return PlainTextResponse('subroute')

routes = [
    Route('/', homepage),
    Mount('/sub', routes=[Route('/', subroute)]),
]

app = Starlette(debug=True, routes=routes)
```

`localhost:8000` and `localhost:8000/` both return "hompage", whereas `localhost:8000/sub` returns a 307 temp redirect to `localhost:8000/sub/` which then returns "subroute".

Small issue and not saying either approach is correct, but I guess I would expect both `Mount` and `Route` to behave the same here.

Using version 13.1.

**Comment by lovelydinosaur** [comment]
> Mounted subroutes require the trailing / to hit their 'root' subroute, whereas regular Routes do not.

Indeed. That's intentional, because a mount point should always be in the form `/path-to-mount/{...}`, so eg all the following are valid...

* `/{...}`
* `/some-path/{...}`
* `/some/path/{...}`

Wheras `/some-path` isn't, because we wouldn't want to match `/some-path{...}`

(Also The HTTP spec mandates that the empty `` path should be treated as equivelent to `/`.)

**Comment by jwtrhs** [comment]
Ah I see, thanks!

So that would mean these two routes would operate a little differently, correct?

```python
routes = [
    Route('/', homepage),
    Mount('/sub', routes=[Route('/', subroute)]),
]

routes = [
    Route('/', homepage),
    Route('/sub', subroute),
]
```

Really I'm just trying to structure my routes/mounts so that they all treat trailing slashes the same. I think my solution is to put the trailing `/` in all my route paths.

```python
routes = [
    Route('/', homepage),
    Route('/sub1/', subroute),
    Mount('/sub2', routes=[Route('/', subroute)]),
]
```

**Comment by and3rson** [comment]
Same issue here: we have REST & WebSocket routes mixed, and since WebSocket app needs to be mounted, we end up having to add slashes at the end of some routes, which is very confusing and error-prone. Example:

```py
def handle_rest(request):
    ...

def handle_websocket(scope, receive, send):
    ...

routes=[
    Route('/foo', handle_rest),       # Path is /foo
    Mount('/bar', handle_websocket),  # Path is /bar/ (trailing slash cannot be avoided, otherwise 307 is returned)
],
```

**Comment by ewjoachim** [comment]
For the lone visitor seeing this issue and wondering what can be done, here's a tip: if you can use a `Mount` because of the trailing slash issue, you can use a `Route` instead.
`Route`s expect a Starlette view instead of a sub ASGI app **except** if the object it receives is an instance of a class (and not a function or a method), in which case, it's considered to be an ASGI App.

So, with the example above:
```python
def handle_rest(request):
    ...

def handle_websocket(scope, receive, send):
    ...

class SubApp:
    def __init__(self, app: starlette.types.ASGIApp):
        self.app = app

    async def __call__(
        self,
        scope: starlette.types.Scope,
        receive: starlette.types.Receive,
        send: starlette.types.Send,
    ) -> None:
        await self.app(scope, receive, send)

routes=[
    Route('/foo', handle_rest),
    Route('/bar', SubApp(handle_websocket)),
],
```

> [!WARNING]
> In that case you need to be explicit about the methods (`GET`, `POST`, ...) otherwise only `GET` is accepted.
