### ISSUE TITLE
[BUG] Routing of encoded slash URL

### ISSUE THREAD

**Issue by jules-ch** [Kludex/starlette#826]
Following https://github.com/tiangolo/fastapi/issues/791: 

It seems starlette is not routing URL with encoded slash in it.

## To Reproduce : 

```python
from starlette.testclient import TestClient

from starlette.applications import Starlette
from starlette.responses import JSONResponse
from starlette.routing import Route


async def get_unit(request):
    unit = request.path_params["unit"]
    return JSONResponse({"unit": unit})


routes = [Route("/units/{unit}", endpoint=get_unit)]

app = Starlette(debug=True, routes=routes)


def test_base():
    client = TestClient(app)
    response = client.get("/units/kg")
    assert response.json() == {"unit": "kg"}


def test_encoded_char():
    client = TestClient(app)
    response = client.get("/units/kg%c2%b2")
    assert response.json() == {"unit": "kg²"}


def test_encoded_slash():
    client = TestClient(app)
    response = client.get("/units/kg%2fs")
    assert response.json() == {"unit": "kg/s"}

```

test_encoded_slash is not working.

## Expected behavior

Starlette is routing the request and retuning the expected json.

## Environment

* OS : Windows 10
* Starlette version : 0.13.1
* Python 3.7.3

## Additional context

Starlette regexp seems fine after inspecting the app routes : `app.routes[0].path_regex` : 

`'^/units/(?P<unit>[^/]+)$'`

```python
>>> import re
>>> pattern=re.compile('^/units/(?P<unit>[^/]+)$')
>>> pattern.match('/units/kg%2Fs')
<re.Match object; span=(0, 13), match='/units/kg%2Fs'>
>>> pattern.match('/units/kg%2Fs').groupdict()["unit"]
'kg%2Fs'
```

**Comment by jules-ch** [comment]
Well the cause seems to be the ASGI spec see : https://github.com/django/asgiref/issues/51#issuecomment-403304610

I think for those kind of usecases we need to use query string which come as a raw string : 

```python

from urllib.parse import unquote

from starlette.applications import Starlette
from starlette.responses import JSONResponse
from starlette.routing import Route
from starlette.testclient import TestClient


async def get_unit(request):
    unit = request.query_params["unit"]
    return JSONResponse({"unit": unquote(unit)})


routes = [Route("/units/", endpoint=get_unit)]

app = Starlette(debug=True, routes=routes)


def test_base():
    client = TestClient(app)
    response = client.get("/units/?unit=kg")
    assert response.json() == {"unit": "kg"}


def test_encoded_char():
    client = TestClient(app)
    response = client.get("/units/?unit=kg%c2%b2")
    assert response.json() == {"unit": "kg²"}


def test_encoded_slash():
    client = TestClient(app)
    response = client.get("/units/?unit=kg%2fs")
    assert response.json() == {"unit": "kg/s"}
```

I'm gonna close this I think, I don't know if we should add a warning in the docs for this ?
Thoughts ?

**Comment by jules-ch** [comment]
They've updated the specs to add raw_path params though : https://github.com/django/asgiref/pull/92#issuecomment-500287263
Updated in 0.8.0 in uvicorn.

**Comment by ichorid** [comment]
While trying to write a FastAPI implementation of a TiddlyWeb plugin for TiddlyWiki, I was bitten by this :shark:  

The API I'm trying to implement uses queries containing `/` character. So, for me, it would be optimal to have an option to disable converting `%2F` to`/`. This conversion breaks the semantics and isolation between the URL path and args, making *every* query unsafe. I don't know how the whole ASGI specification still exists with this mess :crying_cat_face: 

Meanwhile, any advice for a workaround?

**Comment by jules-ch** [comment]
See https://github.com/tiangolo/fastapi/issues/791#issuecomment-742799299

**Comment by lovelydinosaur** [comment]
> I think for those kind of usecases we need to use query string which come as a raw string :

Agreed.

> I'm gonna close this I think, I don't know if we should add a warning in the docs for this ?

Also agreed, yup.

**Comment by mielvds** [comment]
I respectfully disagree with "I think for those kind of usecases we need to use query string which come as a raw string" being a solution. A framework should not dictate how an API should be formed, expecially when it goes against some of the HTTP RFC and the REST best practices.  `/units/kg%c2%b2` is simply not `/units/kg/s` and I should be able to create routes like `/units/kg%c2%b2/name` as well. My main argument would be that disabling this behaviour doesn't affect use cases that don't use it.

**Comment by vmaurin** [comment]
For me it is also a bug that need a fix, the routing should be applied on the incoming URL, prior to decoding (see my post on FastAPI https://github.com/tiangolo/fastapi/discussions/11369 ).

I would be surprise to find out an other HTTP server having the same behavior as Starlette

**Comment by lovelydinosaur** [comment]
> I would be surprise to find out an other HTTP server having the same behavior as Starlette

I think both Flask and Django have the same behavior here.

**Comment by vmaurin** [comment]
@tomchristie I have checked and you are right, Flask and Django have the same issue.

Then I tried java vert.x, then nodejs express, and both work properly.

I will do further tests with nginx/apache rewrite engine, but it seems a "python webserver" kind of issue.

I cannot find a good reason why in a route `/` and `%2F` are handled the same (in a buggy way), while `?` and `%3F` are properly distinct

Percent encoding exists for this reason, to have the proper distinction
https://www.rfc-editor.org/rfc/rfc3986#section-2.2

> If data for a URI component would conflict with a reserved character's purpose as a delimiter, then the conflicting data must be  percent-encoded before the URI is formed.

**Comment by mielvds** [comment]
The fact that flask and Django have the same behaviour doesn't surprise me; they try to align with each others API with Django being a sort of reference case.

During the investigation of this issue, somebody pointed out that Django and/or Flask can be configured to disable this behaviour. FastAPI cannot.

**Comment by vmaurin** [comment]
To be honest, I still have hard time to see any benefit of this behavior. It seems like a bug in django or older, than then get copied everywhere ?

**Comment by vmaurin** [comment]
It is also "fun" to see it is just about the encoded `/`. Encoded `?` as `%3F` is properly parsed as the path data, and not as a query string separator.
With `?` we have the normal/expected/standard behavior
* `foo?bar` => `foo` is the path, `bar` the query string
* `foo%3Fbar` => `foo?bar` is the path, no query string

**Comment by tomchristie** [comment]
Consider...

* `/users/<username>/profile`
* What are you expecting the value of `<username>` to be (in the path keyword arguments.)

**Comment by lovelydinosaur** [comment]
The existing behavior makes sense to me...

* `/users/<username>/profile`
* What do you expect `username` in the path query kwargs to be when `%3F` is included? What are the implications for reverse URL generation?

> somebody pointed out that Django and/or Flask can be configured to disable this behaviour. FastAPI cannot.

Can you point towards what you mean exactly here?

**Comment by vmaurin** [comment]
It is about following URL RFC specifications.

The reasons to have percent encoding are : 
* differentiate a reserved char from the same char but part of the data
* use only ascii for characters outside ascii

As use cases:
* the example for the issue is a good one
* in mine, we allow people to send a unique identifier/slug without restriction then we have endpoint like `/objects/<object_type>/<unique_id>` that results to a 404 with proper URL encoding

And the current behavior is not coherent. There is 19 reserved characters in URL, only encoded `/` is treated as the non encoded one. For all others, it works as specified in the RFC
* `/users/foo%23bar` will pass properly `foo#bar` as username and not as just `foo` considering bar the anchor
* `/users/foo%3Fbar` will pass properly `foo?bar` as username and not as just `foo` considering bar the query string
* so why `/users/foo%2Fbar` then doesn't pass `foo/bar` and instead consider foo and bar as to separated path

Just to repeat, in URL RFC  `/users/foo%2Fbar` and  `/users/foo/bar` are not the same URL

Anyway, I will stop arguing about following the specs, but I am happy to submit a PR to add an option to "fix" the URL behavior (then I am not familiar at all with the code base, so directions are appreciated)

**Comment by mielvds** [comment]
> The existing behavior makes sense to me...
> 
> * `/users/<username>/profile`
> * What do you expect `username` in the path query kwargs to be when `%3F` is included? What are the implications for reverse URL generation?

Hi @tomchristie ,

Sure, if my username would be John/doe, the username can either be `John/doe` or `John%3Fdoe`. Which one is up for debate, but I prefer the former because it's more intuitive and separates concerns. For clarity: in the former the value is decoded before it's added to the kwargs, but after the URL matching. 
Either way, `username` should not be `John` or not match at all. This excludes certain API use cases and that, as @vmaurin points out, is not entirely conform the spec.

The implications for reverse URL generation are I think minor. The distinct values in the kwargs are URL encoded (including slashes) before they are concatenated with `/`, etc. I don't know how this is currently implemented.

But to reverse the perspective and help me understand the other POV: could you give an example in favour of this behaviour or why it makes sense? 


> 
> > somebody pointed out that Django and/or Flask can be configured to disable this behaviour. FastAPI cannot.
> 
> Can you point towards what you mean exactly here?

I'll try to locate the reply and get back to you 

For context: this issue actually originates in the ASGI spec from Django and has been under debate there as well: https://github.com/django/asgiref/issues/51 but the implemented `raw_path` modifier is not a real solution.

**Comment by vmaurin** [comment]
My colleague found the decoding part here, in uvicorn https://github.com/encode/uvicorn/blob/master/uvicorn/protocols/http/httptools_impl.py#L258
So effectively it is really an ASGI thing, but the raw path is available still.

A way to go would be : 
* split the raw path with `/` to have the different segments
* percent decode the segments
* do the routing/path parameter extraction based on the segments
