### ISSUE TITLE
Is it possible to extract the number of in-flight requests?

### ISSUE THREAD

**Issue by deliahu** [Kludex/starlette#836]
Is there a way to extract the total number of in-flight requests (i.e. the number of requests that have been received and not yet responded to)?

If so, how can it be consumed? E.g. can I create an endpoint like /requests which responds with the number? Or perhaps a cron task which can query the number so I could send it to a stats database?

For context, I'd like to trigger autoscaling events based on the number of in-flight requests.

**Comment by lovelydinosaur** [comment]
You'd be able to do this by writing a middleware, that keeps track of whenever requests start and complete, yup.

Given that you'd be running multiple app instances you'd want to persist that information somewhere, so that when you query `/requests` or whatever, you're in a position to retrieve the information for all hosts, rather than just whichever host the request happens to get routed too.

If you've got any questions when working through an implementation here, it might be worth talking them through on the group chat, so we can share whatever progress you make... https://gitter.im/encode/community

**Comment by deliahu** [comment]
@tomchristie Thank you, I will think about implementation details, and follow up on the gitter!
