### ISSUE TITLE
Possible to parse uploaded files while they are being uploaded?

### ISSUE THREAD

**Issue by simonw** [Kludex/starlette#849]
I'm using Starlette to write code that accepts a potentially huge CSV file upload from a user and writes that CSV file into a SQLite database: https://github.com/simonw/datasette-upload-csvs

I'm adding progress bars (via XHR) right now - https://github.com/simonw/datasette-upload-csvs/pull/5 - and the progress bar makes it obvious that after the CSV has uploaded there's a significant pause while it is being processed.

This is because when I run `await request.form()` Starlette handles the entire upload, writes it to disk, then hands me a `SpooledTemporaryFile` I can start working with.

CSV is a format that is very supportive of processing as a stream. Is there a sensible way, working with Starlette and `multipart/form-data`, to stream the bytes that are being uploaded to my own handler function while the upload is continuing? Some kind of `async for chunk in file_being_uploaded` mechanism?

It looks like I can use `async for chunk in request.stream():` for this, but presumably that means I have to roll my own parsing of the incoming `multipart/form-data` data. So two questions:

- Is there an elegant pattern for parsing incoming `multipart/form-data` file uploads as a stream in this way?
- Is this a feature that Starlette could offer as part of the Starlette API?

**Comment by simonw** [comment]
I found this code in Starlette's internals:

https://github.com/encode/starlette/blob/3de541cfe299a2a6a3741937633c81ad99d65a6a/starlette/formparsers.py#L216-L231

I think what I want is some kind of mechanism such that the `await file.write(message_bytes)` line there writes to a file object that I control, as opposed to the `UploadFile()` object that Starlette is creating.

**Comment by simonw** [comment]
Similar discussions in #697 and #388 (which I participated in and then forgot about!)

**Comment by lovelydinosaur** [comment]
https://github.com/simonw/starlette/commit/d53f89d39b4d6451d82e679fffbe0bea342296fc would be a good start here yup. (Alternately, have it optionally configured on `__init__`?)

**Comment by adriangb** [comment]
I feel like form parsing and files in general are a non-customizable corner of Starlette. Maybe we can have some parameters to Request.form() to set the target FormParser class and/or UploadFile implementation.

Use cases I can think of:
1. Doing something other than writing to a file (for example, streaming the bytes into S3/GCS or the use case here).
2. Customizing the memory limit for SpooledTemporaryFile.
3. Using custom logic for deciding what to handle as an UploadFile and what to handle as a form (for example to support binary data that is not a file)

**Comment by lovelydinosaur** [comment]
I think at the moment we've just got to treat this as out of scope.

Customisable request parsing is one of the very few areas where I *could* potentially see us adding as a feature to Starlette. If we did this we'd take a similar approach to REST frameworks customisable parsers, and it'd allow folks to deal with requests such as this, and https://github.com/encode/starlette/issues/697 and https://github.com/encode/starlette/issues/388.

But for now I'd rather we just punt on any of that, treat Starlette as being in feature pause for a while, and just make sure to let things bed in, deal with any outright bugs, and make sure we've got a really nicely manageable fairly minimal project.

**Comment by remram44** [comment]
This is disappointing. To be honest this was the main reason I was looking into upgrading from Tornado to Starlette.

I don't understand why reading uploaded data asynchronously rather than reading the whole file and handling it synchronously is not in scope for an asynchronous web framework, but this is your call to make.

There are easy-to-use/integrate tools like [streaming-form-data](https://github.com/siddhantgoel/streaming-form-data). I think that would have been a great addition to Starlette, but if you'd rather we replace Starlette's parser with that explicitly to get async requests, ok.

**Comment by lovelydinosaur** [comment]
> I don't understand why reading uploaded data asynchronously rather than reading the whole file and handling it synchronously is not in scope for an asynchronous web framework, but this is your call to make.

You can asynchronously stream the request data and plug that into whatever you'd like...

```python
async for chunk in request.stream():
    ...
```

I'm not 100% against us *also* considering a customisable request parsing API similar to REST framework's `parser_classes`, so that you can drop-in different parsing implementations on top of that, but I don't think we should be considering that an "issue" at this point in time.

It's not realistic for us to consider feature work unless the existing backlog is completely sorted out. Better that we close off possible-future-feature work, and make sure that the functionality we do provide is without issue, and thoroughly documented.

**Comment by adriangb** [comment]
> You can asynchronously stream the request data and plug that into whatever you'd like...

I feel like this is only partially true: because you have no hook to replace `Request` or anything else, while you can grab the stream and use it manually this breaks the rest of the ecosystem because the behavior of interacting with that request object later on is different (e.g. `Request._form` is never saved).

Further, you'd have to re-implement form parsing yourself, which is a tricky thing to do  (about 5% of the Starlette codebase). It feels like a lot to ask of users when maybe they just wanted to add a single function call to `UploadFile.write` to have a progress bar.
