### ISSUE TITLE
[QUESTION] Starlette async usage

### ISSUE THREAD

**Issue by crotaoryx** [Kludex/starlette#863]
Hi guys! I'm sorry for stupid question in advance, but it seems this place has more starlette developers then any other and i hope someone can help me. I'm just beginner with starlette/async python and trying understand how it works. I wrote this simple code:

```python
from starlette.applications import Starlette
from starlette.responses import JSONResponse
from starlette.routing import Route
from datetime import datetime
import asyncio


async def test():
    await asyncio.sleep(2)


async def page(request):
    check = []
    check.append(str(datetime.now().strftime('%H:%M:%S')))
    await test()
    await test()
    await test()
    await test()
    check.append(str(datetime.now().strftime('%H:%M:%S')))

    return JSONResponse('---'.join(check))


app = Starlette(debug=True, routes=[
    Route('/', page),
])

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, port=8000, host='0.0.0.0')

```

and how i think this will work - starlette receives request, run "page" function and inside i have 4 "test" functions with sleep(2). I thought that it will take 2 seconds to complete, but instead of 2 seconds i see 8, like it works as usual sync code.
What is my mistake? I'm really appreciate  any help)
Thanks!

**Comment by lovelydinosaur** [comment]
Hiya! No need to apologize - it's not a "stupid question". (Although I think we will want to start directing usage questions to https://gitter.im/encode/community rather than the issue tracker.)

These calls run sequentially...

```python
    await test()
    await test()
    await test()
    await test()
```

You'd need to look at eg. https://docs.python.org/3/library/asyncio-task.html#running-tasks-concurrently for running tasks concurrently.

In general though you *won't* typically want to be running tasks concurrently within an endpoint all that often. (The async benefit here is more that the server is typically able to handle a greater overall number of incoming requests concurrently.)
