### ISSUE TITLE
Unexpected disconnect when using asyncio.wait()

### ISSUE THREAD

**Issue by kmani314** [Kludex/starlette#871]
I'm trying to listen for data on a websocket while simultaneously doing some work in another function. 
```
data = await websocket.receive_json()
while True:
    try:
        done, pending = await asyncio.wait({eval_worker(data, websocket), websocket.receive_json()}, return_when=asyncio.FIRST_COMPLETED)
        # do stuff with done
    except Exception:
        return
```
It results in this error: ```
ERROR:    Task exception was never retrieved
future: <Task finished name='Task-9' coro=<WebSocket.receive_json() done, defined at /***/venv/lib/python3.8/site-packages/starlette/websockets.py:94> exception=WebSocketDisconnect(1000)>
Traceback (most recent call last):
  File "/***/venv/lib/python3.8/site-packages/starlette/websockets.py", line 98, in receive_json
    self._raise_on_disconnect(message)
  File "/***/venv/lib/python3.8/site-packages/starlette/websockets.py", line 80, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1000```
I passed the websocket object to the function so that it can send data while it is also listening. I understand that this could be problematic, but even when I don't pass the websocket to the function it results in the same disconnect error.
Any insight?

**Comment by AsgeirOutland** [comment]
When you run asyncio.wait(...) you create two tasks. One of which you don't await/get the result from, because as far as I can tell you're ignoring pending. Meaning, when the code loops back to the next asyncio.wait(...) call and when that call returns, the previous pending gets deleted, and so does the task inside of it, causing the task to throw an exception because it was not processed correctly.
