### ISSUE TITLE
How to create a http request from starlette?

### ISSUE THREAD

**Issue by jodusan** [Kludex/starlette#872]
If I need to hit some external GET api, how do I do it from starlette? Or do I use some other library like requests?

**Comment by LostLuma** [comment]
You need to use another library in order to do this, however you shouldn't use requests specifically as it will block and prevent other tasks from running in the event loop. Take a look at [aiohttp](https://github.com/aio-libs/aiohttp), [httpx](https://github.com/encode/httpx) or another library instead :)

**Comment by jodusan** [comment]
thats what I thought, thanks!!
