### ISSUE TITLE
Add support for Google Cloud Storage and AWS S3

### ISSUE THREAD

**Issue by lorddaedra** [Kludex/starlette#873]
https://www.starlette.io/staticfiles/

It's looks as good idea to add support for private storage buckets.

It can be useful, for example, for creating static pypi repository (via dumb-pypi generator) on google cloud bucket and using Starlette as proxy between Google Cloud Storage bucket and end user (with pip or poetry).

**Comment by lovelydinosaur** [comment]
I'd suggest including `STATIC_URL` in your template contexts, and using `{STATIC_URL}/whatever.css` in the template.

You'll probably also want to do some config setup so that in development you serve from `http://127.0.0.1/statics` and include StaticFiles in that case.

Happy to discuss any future ideas around this at https://gitter.im/encode/community
