### ISSUE TITLE
API to parse URLs

### ISSUE THREAD

**Issue by dneuhaeuser-zalando** [Kludex/starlette#877]
It would be great, to have an API to parse URLs without calling the corresponding endpoint.

We'd like to have an API in which resources are referred to by URI instead of some id. This means that we occasionally need to parse those, when they occur in a request body. It would be nice not to have to write our own code for parsing those urls.

**Comment by lovelydinosaur** [comment]
Hi there, thanks for getting involved. 😃

I'm closing this off for now, since we're moving to a "maintainer driven" policy on our issue tracker & pull request spaces. This will gradually help us ensure that these spaces do a good job of properly reflecting the ongoing project priorities.

The best places to start with this are instead [the chat room](https://gitter.im/encode/community), or [the discussion group](https://discuss.encode.io/).

Many thanks. 💛✨

It's possible that there's something in here that'd be actionable, but it's not sufficiently clear from the description exactly what you're looking for - do you mean "given a URL, we'd like to know which endpoint/kwargs it'll route to or something else?"

[Read more about our contribution guidelines.](https://github.com/encode/.github/blob/master/CONTRIBUTING.md)
