### ISSUE TITLE
return response directly in dependency

### ISSUE THREAD

**Issue by jendy2012** [Kludex/starlette#897]
Is your feature request related to a problem
Yes.
Currently, fastapi support raise HttpExpection in dependency and return a response struct like this:
{detail: "error"}.

I want to be able to return a self-defined response, but I can't because now I can only return {"detail": xxxxx}

The solution you would like
For example, I want to
return HttpException(status_code=200, data={"haha":"Hello", "code": 20000}),
and the frontend recieve successful reponse struct like this:
{
data:{"haha":"Hello", "code": 20000},
code: 200
}

Thank you!

**Comment by lovelydinosaur** [comment]
Hi there, thanks for getting involved. 😃

I'm closing this off for now, since we're moving to a "maintainer driven" policy on our issue tracker & pull request spaces. This will gradually help us ensure that these spaces do a good job of properly reflecting the ongoing project priorities.

The best places to start with this are instead [the chat room](https://gitter.im/encode/community), or [the discussion group](https://discuss.encode.io/).

Many thanks. 💛✨

[Read more about our contribution guidelines.](https://github.com/encode/.github/blob/master/CONTRIBUTING.md)
