### ISSUE TITLE
get staticfile failed. 

### ISSUE THREAD

**Issue by mulanyt** [Kludex/starlette#937]
Following the docs, it seems all right. But if the endpoint that looks like "/blog/x", it will gets a 404 error(GET /blog/static/js/jquery.min.js HTTP/1.1 404). i check the file is in /static/js.
The structure of files as follow:
static
----img
--------xx.jpg
----css
--------xx.css
----js
--------jquery.min.js
templates
----index.html
----blog.html
app.py

**Comment by lovelydinosaur** [comment]
Hi there, thanks for getting involved. 😃

I'm closing this off for now, since we're moving to a "maintainer driven" policy on our issue tracker & pull request spaces. This will gradually help us ensure that these spaces do a good job of properly reflecting the ongoing project priorities.

The best places to start with this are instead [the chat room](https://gitter.im/encode/community), or [the discussion group](https://discuss.encode.io/).

Many thanks. 💛✨

[Read more about our contribution guidelines.](https://github.com/encode/.github/blob/master/CONTRIBUTING.md)
