### ISSUE TITLE
[Feature] Allow overriding of qraphiql html

### ISSUE THREAD

**Issue by lioman** [Kludex/starlette#953]
`graphiql` uses sources, that are embedded via jsdekivr.net. In some networks hosts like these are prohibited, or there is no internet access at all. On the other side there are several other, enhanced graphql frontends as proposed in #753 or #698 

A simple approach is to add possibility to overwrite the default graphiql html code.

**Comment by lioman** [comment]
Would be nice, if somebody has a look at my pull request. I want to know if I need to rework something, or if it can be merged.

**Comment by lovelydinosaur** [comment]
I'm currently a bit reluctant to make any changes in the GraphQL implementation at all, since I'd really prefer to eventually drop it from Starlette in favour of someone taking on the workload as a third party package instead.

There's a lot of work that's gone into making sure components are really neatly decoupled in Starlette, so it's not a terrible idea to instead copy the GraphQL app into your own codebase, and then make any adjustments from there, rather than holding out for "let's get this changed in core".

**Comment by lioman** [comment]
This is understandable, but I still hope it gets merged. Now you have to override the `GraphQLApp` and its `handle_graphiql` method in your code. With every downside of this approach, because you need to adapt your implementation to changes upstream. This is a valid approach if you change bigger things, but here you just want to override a static constant.

**Comment by JayH5** [comment]
Thank you for filing this issue. We have decided to deprecate GraphQL support within Starlette itself so I am going to close this issue. See #619.
