### ISSUE TITLE
Converge {starlette,httpx}.{Request,Response}

### ISSUE THREAD

**Issue by julien-c** [Kludex/starlette#961]
This is not really an issue but more of a question/observation.

I'm using both starlette and [httpx](https://github.com/encode/httpx) to implement a reverse proxy.

The classes being subtly different, piping a Starlette request into an httpx request, then piping a httpx response into a Starlette response is doable, but a little tedious:

```python
async def proxy_model_forward(request: starlette.requests.Request):
    # ...
    # do some stuff depending on conditions

    body = await request.body()
    r: httpx.Response = await CLIENT.post(
        endpoint, data=body, headers=request.headers.raw
    )
    headers = dict(r.headers.items())
    return Response(content=r.content, status_code=r.status_code, headers=headers)

```

Was any thought given to make classes' APIs a little closer, for instance for header formats?

Thanks for reading.

**Comment by lovelydinosaur** [comment]
So, yeah I'm up for bringing them into line, at some point, but it'd need some serious thinking about.

The `httpx` API design came later on, and was a bit different because we had a guiding star of wanting to be ~API compatible with requests where possible.

Incidentally you might find this proxy implementation useful too...  https://gist.github.com/tomchristie/5765e10a90a41c7e57470e2dc700f9db
