### ISSUE TITLE
Is it okay to use sqlalchemy in async mode without using databases?

### ISSUE THREAD

**Issue by balukrishnans** [Kludex/starlette#969]
Hai friends,
Is it okay to use sqlalchemy in the async mode without using databases?
(need async level operation)

**Comment by Chaostheorie** [comment]
databases acts as driver for sqlalchemy. You can use it in async mode with an appropiate driver (url: `driver://…`). Though I would highly recommend [Gino](https://python-gino.org/docs/en/master/index.html) because it's built on top of sqlalchemy for async operations. It also has an [Starlette Extension](https://python-gino.org/docs/en/master/reference/extensions/starlette.html).

**Comment by erewok** [comment]
In addition to Gino, you can also use Sqlalchemy core with [`asyncpg`](https://magicstack.github.io/asyncpg/current/) as well as [`asyncpgsa`](https://asyncpgsa.readthedocs.io/en/latest/). This is less ORM-ish, though, and more towards using Sqlalchemy core to build up your queries, which get executed by a connection object.

**Comment by erewok** [comment]
In the future, questions like this are well-suited to the community discussion board instead of as issues: https://discuss.encode.io/c/starlette
