### ISSUE TITLE
Consider removing the Middleware class?

### ISSUE THREAD

**Issue by retnikt** [Kludex/starlette#971]
Sorry if this is unwelcome, but I think the `Middleware` class (in `starlette/middleware/__init__`, not `BaseMiddleware`) seems pretty pointless. It is nothing more than a re-invented `namedtuple` storing a `cls`, which could just be any callable, and `options`. Could it be removed, and adding middleware simplified down to closures or other callables instead of several layers of classes?
This [talk](https://www.youtube.com/watch?v=o9pEzgHorH0&t=180) shows how these abstractions add unnecessary complexity, and Starlette's middleware system seems a pretty good example of "a class with two methods, one of which is `__init__`".

Could this:
```python
class MyMiddleware:
    def __init__(self, app, foo_option):
        self.app = app
        self.foo_option = foo_option
    async def __call__(self, scope, receive, send):
        # do something with scope_receive, send
        await self.app(scope, receive, send)
app = Starlette(
    middleware=[Middleware(MyMiddleware, foo_option="spam")]
)
```
be boiled down to:
```python
async def my_middleware(app):
    async def process(scope, receive, send):
        # do something with scope, receive, send
        await app(scope, receive, send)
app = Starlette(middleware=[my_middleware])
```
or, where options need to be passed at runtime (most of the time they don't, and can be read from the application's config)
```python
def my_middleware(foo_option):
    async def inner(app):
        async def process(scope, receive, send):
            # do something with scope, receive, send
app = Starlette(middleware=[my_middleware(foo_option="spam")]))
```

Also, I think the whole system of building the middleware stack could be removed, since `add_middleware`, `add_exception_handler`, and the `middleware` decorator are already discouraged:
> ```python
> # The following usages are now discouraged in favour of configuration.
> #  during Starlette.__init__(...)
> ```

**Comment by erewok** [comment]
I don't think this feedback is unwelcome but it's probably not too actionable at this time. In general, I agree with the criticism that having to build a list of middleware by wrapping them all in the `Middleware` class is a user experience that could be improved, but this is due to shift to the newer style of adding middleware to the `Starlette` application instance. I think we should probably come up with a more specific proposal, though, and leave the `Middleware` class in the codebase for now until we have a design that improves upon this and is in keeping with the generic-ASGI-middleware nature Starlette has been sticking to so far.
